### ISSUE TITLE
reset() error

### ISSUE THREAD

**Issue by Jonfor** [intercom/intercom-android#188] opened 2016-03-31 22:00 UTC
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Android version: 1.1.16
  - Android OS version: 6.0.1
  - Android Device: Nexus 5X

## Expected behavior
Intercom.client().reset() would not complain
## Actual behavior
Intercom.client().reset() throws an error
## Steps to reproduce
 1. Log into app and connect to Intercom
 2. Log out

## Logs
E/Intercom-Android: ERROR: Api call failed: application interceptor io.intercom.android.sdk.api.IdentityInterceptor@b969f7 returned null

**Comment by harkin** [comment] 2016-04-01 09:59
:+1: reproduced and fixed, fix will be in the next version

**Comment by Jonfor** [comment] 2016-04-01 13:50
:ok_hand:

**Comment by harkin** [comment] 2016-04-18 10:49
this change is live since 1.1.17, forgot to close the issue :(

**Closed by harkin** 2016-04-18 10:49 UTC
