### ISSUE TITLE
NPE in NexusSocket.onOpen()

### ISSUE THREAD

**Issue by cheah** [intercom/intercom-android#138] opened 2015-10-09 03:40 UTC
Crashlytics log: http://crashes.to/s/26fd125823d

**Comment by harkin** [comment] 2015-10-09 10:26
That line it's crashing on is invoking a method on an enum which (normally) isn't null. 

It seems a little unusual that this is only happening on devices running kitkat. Are you multidexing your app and/or are you close to the method count limit?

Do you run proguard on your app? Proguard can simplify enums to int fields but it shouldn't be doing that here.

Is this something you can reproduce in house?

**Comment by cheah** [comment] 2015-10-09 10:41
Yes. We have a Nexus 7 device that consistently crashes due to this.

No proguard. But we do have MultiDex with 2 dex files.

**Comment by harkin** [comment] 2015-10-09 10:51
Just to be sure, are you using the [support multidex library](https://developer.android.com/tools/support-library/features.html#multidex) v1.0.1 and extending/installing the [MultiDexApplication](https://developer.android.com/reference/android/support/multidex/MultiDexApplication.html)?

Could you try updating to v1.1.7 of the Intercom library and see if you still get this crash? We didn't change anything that would directly fix this but there are a lot of other small bug fixes in there, and we updated the underlying websocket layer for realtime (which is very close to this crash)

**Comment by cheah** [comment] 2015-10-09 11:00
We are using the v1.0.1 multidex library but instead of extending the MultiDexApplication class we are doing this instead:

```
@Override
protected void attachBaseContext(Context base) {
    super.attachBaseContext(base);
    MultiDex.install(this);
}
```

Will try to update to the latest library and report back.

**Comment by harkin** [comment] 2015-10-09 11:14
That looks fine to me, so we can rule out a multidex issue. I'm going to look into this from our side and see what might be going wrong. Eager to hear how updating goes and if it's still present

**Comment by cheah** [comment] 2015-10-15 03:38
Upgraded to `1.1.7` and it seems not to crash anymore. Thanks!

**Comment by harkin** [comment] 2015-10-15 12:22
@cheah great to hear :) 

I haven't found out exactly what was going wrong yet, I suspect it's something in the underlying websocket layer. I'm going to keep looking and I'll update this issue if I find out. Gonna close it for now since it's working for you, reopen or let us know if you have any issues!

**Closed by harkin** 2015-10-15 12:22 UTC
