### ISSUE TITLE
Websocket protocol not supported

### ISSUE THREAD

**Issue by faizalzakaria** [intercom/intercom-android#74] opened 2015-05-13 08:36 UTC
I encountered this problem while testing intercom in 1 of our test device.

```
Upgrade:                websocket
Connection:             Upgrade
Sec-WebSocket-Key:      /L5KQXBQY5GRwmMDk9l+jg==
Sec-WebSocket-Version:  13
Host:                   nexus-router-b-7.intercom.io
Accept-Encoding:        gzip
User-Agent:             okhttp/2.3.0
```

```
Date:                        Wed, 13 May 2015 08:33:33 GMT
X-Atmosphere-first-request:  true
X-Atmosphere-tracking-id:    9414f2e0-b2ee-4f9e-bc9f-dd79dcfc75b8
X-Atmosphere-error:          Websocket protocol not supported
Transfer-Encoding:           chunked
```

What could it be ?

**Comment by Harkin** [comment] 2015-05-13 09:23
What device did this happen on?

**Comment by faizalzakaria** [comment] 2015-05-13 10:21
Hey @Harkin 
samsung galaxy grand 2 with android version 4.4.2
Android SDK version 19

**Comment by Harkin** [comment] 2015-05-13 10:47
Thanks, we're looking into this on our end now. 

Just to be super clear this was a message that got logged and it didn't actually cause a crash or have any adverse effects on your app?

**Comment by faizalzakaria** [comment] 2015-05-13 11:45
No crashed yes. We intercept the request, and we can see what being called to intercom. And the response is as mentioned in the first post.

Due to this, we are unable to get any messages from intercom.

**Comment by Harkin** [comment] 2015-05-13 12:24
We SSL pin requests from the integration to our backend. If you're trying to intercept those requests then nothing will work, pretty sure it's an SSL handshake error that you'll be seeing.

I'd advise not trying to intercept things in the *.intercom.io domain

**Comment by faizalzakaria** [comment] 2015-05-14 02:39
> We SSL pin requests from the integration to our backend. If you're trying to intercept those requests then nothing will work, pretty sure it's an SSL handshake error that you'll be seeing.

We added SSL of course to forward to your server. Obviously not a SSL handshake prob. Https works just fine.

**Comment by Harkin** [comment] 2015-05-14 08:39
Sorry I wasn't clear in my last comment. 

We use websockets for realtime. That error you saw was with websockets but we don't rely on realtime for the integration to work properly. If something isn't working it's for a different reason than that error. We're looking into why you were getting a 501 from that channel.

What isn't working?

**Comment by faizalzakaria** [comment] 2015-05-15 03:05
Hey @Harkin ,

Things that arent working is as such : 
- Unable to get message from intercom.io
- Unable to send back (reply to) to intercom.io server.

Obviously from the error, 501, the socket is failed to established, hence the reason why it unable to send/receive to/from the intercom server.

Appreciate your insight on this.

p/s: It works for some device.

Apart from that,
We published the Android release few hours ago, and we got a lot of crashes few minutes after that from a user. Sad to tell you that we have to revert that back. (I'll create a new issue for that).

Thanks.

**Comment by Harkin** [comment] 2015-05-15 11:02
Neither of those problems are caused by the 501s you're seeing though I suspect the cause is the same. What are you using to intercept the traffic from your app? As well as the 501s you should be seeing other failed requests. 

I've been digging around looking at why your API requests are failing and the reason is that you have multiple users with the same email address on your Intercom app. If you register with email in the sdk and there are multiple users with that email in your Intercom app the lookup fails on our backend because we don't know which user to match. 

I'd suggest switching to registering with a unique user id per user

**Comment by faizalzakaria** [comment] 2015-05-19 02:11
Hey @Harkin ,
We are importing the data from Mixpanel. 
I believe it won't be any problem if we are only using mobile to import/setup the data, wondering what `field` should we fix in intercom ?

**Comment by cyrille-duriana** [comment] 2015-05-19 03:03
@Harkin I work with @faizalzakaria -- what is weird is that it works with iOS, Android 5.1 and not Android 4.4.2. We tested in the same conditions, with the same users.

For instance, conversion ID 896187322 -- on Android 4.4.2, one couldn't answer && on the dashboard, it was written as "not seen". We opened it then on iOS, and there no problem. You can check the logs for yourself.
![ios](https://cloud.githubusercontent.com/assets/11973998/7694541/7b6d06ea-fe14-11e4-8feb-5ad1229661fa.png)
![android4 4 2](https://cloud.githubusercontent.com/assets/11973998/7694672/1b553c44-fe16-11e4-8cdf-f26e26dce215.png)
![android5 1](https://cloud.githubusercontent.com/assets/11973998/7694673/1b56b9de-fe16-11e4-9300-64cafa007668.png)


For you to check it out, conversation id 6063892 was opened on Android, and is was not marked as seen. Then, upon opening with Android 5.1 it was working fine.
Conversation id 896184979 was only opened on iOS, and was correctly marked as seen, and replied to.

All tested with the same company account, same user account, etc, only difference was the device. We have 3 Android 4.4.2 devices, all difference models. Except that the os version is the same and all of them are Samsung, they are different.

**Comment by Harkin** [comment] 2015-05-19 11:34
@cyrille-duriana This is weird.

In the logs I can see the successful requests for conversation with id `896184979`. Is `6063892` the correct conversation id for the other conversation with the message that failed to send?

One thing I did notice in the logs is that requests are coming in with a `Content-Type: */*` header which is wrong and should cause failures. I don't think this is something you could be changing in the sdk (you'd need to be changing some internal parts of the sdk). You aren't the only person we've found that sends requests with that content type (coming from both iOS and Android). We're wondering if an ISP or cellular network provider is changing the header.

From the screenshots it looks like all the phones are on wifi. Could you confirm this and also let me know which ISP this is? Also could you let me know which country you're in? If possible could you try checking a different wifi network or cellular network.

**Comment by Harkin** [comment] 2015-05-20 10:29
After some investigating we think the `Content-Type` header might be a red herring

**Closed** 2015-06-09 16:09 UTC
