### ISSUE TITLE
java.lang.Thread.nativeCreate(Native Method)

### ISSUE THREAD

**Issue by noinlijin** [intercom/intercom-android#393] opened 2017-08-03 02:07 UTC
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Android version: 3.2.6
  - Android OS version: 6.0.1 (23)
  - Android Device: Xiaomi:Redmi 4:arm64-v8a

## Expected behavior
The engineer told me okhttp‘s native thread caused outOfMemory,our app did not use okhttp,Intercom used this Third party library
## Steps to reproduce
Our bug statistics system, detected this bug appeared 7 times on different users' devices    
![image](https://user-images.githubusercontent.com/3073370/28902747-8d063430-7833-11e7-9f7e-26b47308bd43.png)

## Logs
![image](https://user-images.githubusercontent.com/3073370/28902705-4b95eb6c-7833-11e7-8ec2-544f2598b621.png)

**Comment by DaleCantwell** [comment] 2017-08-04 10:52
Hi @noinlijin 
I'm not sure Intercom is the cause here. I'm not confident this error log is giving the correct source of the issue. The OkHttp thread was definitely spun up by Intercom but I would be surprised if that is the cause of the OutOfMemoryError. Were there any other threads present in that crash log? It is much more likely something else caused this and that OkHttp was one of many threads that died as a result.
Thanks,
Dale

**Comment by skylerwshaw** [comment] 2017-08-08 13:07
@noinlijin You have reported OutOfMemory errors across several issues. Have you inspected your application for heavy memory use or profiled any potential memory leaks? If your application is already has memory problems, launching Intercom can make a crash occur since the SDK is unable to use the application memory space without hitting the limit.

**Comment by noinlijin** [comment] 2017-08-09 01:27
I use aliyun mqc free test 30 devices, [here](http://mqc.aliyun.com/)

**Comment by noinlijin** [comment] 2017-08-09 01:28
every day can free test 30 devices two times in random devices

**Comment by ronocod** [comment] 2017-09-08 12:30
Closing this, the error here appears to be happening on the UI thread, not the OkHttp thread. Only the main thread will call `ActivityThread.main()`.

It looks like this isn't caused by our code, and that this crash reporting service is showing the wrong name for this thread.

**Closed by ronocod** 2017-09-08 12:30 UTC
