### ISSUE TITLE
Intercom Activity fails to start on android 19 4.4.2

### ISSUE THREAD

**Issue by abhinovg** [intercom/intercom-android#284] opened 2016-11-10 12:59 UTC
## Version info
  - Intercom for Android version: 
  - Android OS version: (Android 4.4.2, API 19)
  - Android Device: Samsung SM-N9005

## Expected behavior
The Intercom messenger opens normally and user can change / see past chats

## Actual behavior
Application crashes, only only on API 19 from testing 21 and above worked okay. 

## Steps to reproduce
 1. Initial Inter com as per documents
 2. Update User with email and email
 3. call Intercom.client().displayMessenger();
 4. Application crashing on 4.4.2 api 19, work fine in the simulator, API 19

Permissions in manifest:
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_INTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

## Logs
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process:app.com.au.andriod, PID: 25153
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{app.com.au.andriod/io.intercom.android.sdk.activities.IntercomMessengerActivity}: java.lang.NullPointerException
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2282)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2340)
                      at android.app.ActivityThread.access$800(ActivityThread.java:157)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1247)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:157)
                      at android.app.ActivityThread.main(ActivityThread.java:5293)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
                      at dalvik.system.NativeStart.main(Native Method)
                   Caused by: java.lang.NullPointerException
                      at io.intercom.android.sdk.inbox.InboxFragment.displayEmptyView(InboxFragment.java:402)
                      at io.intercom.android.sdk.inbox.InboxFragment.onStateChange(InboxFragment.java:369)
                      at io.intercom.android.sdk.inbox.InboxFragment.onStateChange(InboxFragment.java:57)
                      at io.intercom.android.sdk.utilities.ChangeSubscriber.onStateChange(ChangeSubscriber.java:33)
                      at io.intercom.android.sdk.store.Store.subscribe(Store.java:87)
                      at io.intercom.android.sdk.store.Store.subscribeToChanges(Store.java:96)
                      at io.intercom.android.sdk.inbox.InboxFragment.onCreate(InboxFragment.java:124)
                      at android.support.v4.app.Fragment.performCreate(Fragment.java:2075)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1060)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
                      at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1682)
                      at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
                      at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
                      at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:181)
                      at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1189)
                      at android.app.Activity.performStart(Activity.java:5399)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2255)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2340) 
                      at android.app.ActivityThread.access$800(ActivityThread.java:157) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1247) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:157) 
                      at android.app.ActivityThread.main(ActivityThread.java:5293) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081) 
                      at dalvik.system.NativeStart.main(Native Method)

**Comment by ronocod** [comment] 2016-11-10 13:03
Duplicate of https://github.com/intercom/intercom-android/issues/282, this issue is fixed in 3.0.12.

**Closed by ronocod** 2016-11-10 13:03 UTC

**Comment by shaibar** [comment] 2016-12-21 10:58
@ronocod Still happens in  3.0.17
