### ISSUE TITLE
Permission crash when launching on android 23 device (6.0)

### ISSUE THREAD

**Issue by elikohen** [intercom/intercom-android#128] opened 2015-09-02 14:45 UTC
We just tested compiling our app (with intercom included) over android 23, everything worked fine on 22 or below devices but when running on android 23 emulator we got this crash:

```
09-02 16:42:02.923    3892-3892/com.ztory.main E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.ztory.main, PID: 3892
    java.lang.RuntimeException: Unable to create service io.intercom.android.sdk.preview.PreviewService: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@a268d -- permission denied for this window type
            at android.app.ActivityThread.handleCreateService(ActivityThread.java:2887)
            at android.app.ActivityThread.-wrap4(ActivityThread.java)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@a268d -- permission denied for this window type
            at android.view.ViewRootImpl.setView(ViewRootImpl.java:591)
            at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:310)
            at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
            at io.intercom.android.sdk.preview.PreviewService.init(PreviewService.java:206)
            at io.intercom.android.sdk.preview.PreviewService.onCreate(PreviewService.java:123)
            at android.app.ActivityThread.handleCreateService(ActivityThread.java:2877)
            at android.app.ActivityThread.-wrap4(ActivityThread.java)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by harkin** [comment] 2015-09-02 14:48
Thanks for reporting this!

This is a dupe of https://github.com/intercom/intercom-android/issues/116 there's more context on that issue so I'm going to close this and update that issue

I'm actively working on fixing this and other permission issues, I expect to have a release that works on M in the next day or two

**Closed by harkin** 2015-09-02 14:48 UTC

**Comment by elikohen** [comment] 2015-09-02 14:49
Wow, sorry about that, i didn't see that one. Thanks for the info!
