### ISSUE TITLE
A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.

### ISSUE THREAD

**Issue by Amagi82** [intercom/intercom-android#224] opened 2016-07-25 22:55 UTC
## Version info
  - Intercom for Android version: 3.0.1
  - Android OS version: 6.0.1
  - Android Device: Nexus 6

## Behavior
When using Intercom.client().displayMessageComposer(), displayMessenger(), or displayConversationsList(), clicking on a conversation from the intercom screen or starting a new one, the below errors are spammed (usually 3 pairs of messages per click). No crash or any other ill effects noticed. 

#### Devices tested: 
HTC Incredible running 4.4.4: No errors
HTC DNA running 4.4.2: No errors
Nexus 6 running 6.0.1: Errors shown

#### Emulators tested:
API 23: Only I/OMXClient: Using client-side OMX mux., not the other error
API 21: No errors

## Logs
```
07-25 15:30:51.304 24346-24611/com.{mypackagename} I/OMXClient: Using client-side OMX mux.  
07-25 15:30:51.315 24346-24611/com.{mypackagename} E/OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.  
07-25 15:30:51.352 24346-24614/com.{mypackagename} I/OMXClient: Using client-side OMX mux.  
07-25 15:30:51.357 24346-24614/com.{mypackagename} E/OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.  
07-25 15:30:51.403 24346-24617/com.{mypackagename} I/OMXClient: Using client-side OMX mux.  
07-25 15:30:51.413 24346-24617/com.{mypackagename} E/OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.  
07-25 15:30:51.454 24346-24628/com.{mypackagename} I/OMXClient: Using client-side OMX mux.  
07-25 15:30:51.458 24346-24628/com.{mypackagename} E/OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.  
07-25 15:30:55.638 24346-24697/com.{mypackagename} I/OMXClient: Using client-side OMX mux.  
07-25 15:30:55.644 24346-24697/com.{mypackagename} E/OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.  
07-25 15:30:55.691 24346-24700/com.{mypackagename} I/OMXClient: Using client-side OMX mux.  
07-25 15:30:55.695 24346-24700/com.{mypackagename} E/OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.  
07-25 15:30:55.730 24346-24703/com.{mypackagename} I/OMXClient: Using client-side OMX mux.  
07-25 15:30:55.734 24346-24703/com.{mypackagename} E/OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.  
07-25 15:30:55.777 24346-24706/com.{mypackagename} I/OMXClient: Using client-side OMX mux.  
07-25 15:30:55.784 24346-24706/com.{mypackagename} E/OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.  
07-25 15:32:18.727 24346-25882/com.{mypackagename} I/OMXClient: Using client-side OMX mux.  
07-25 15:32:18.913 24346-25882/com.{mypackagename} E/OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.  
07-25 15:32:18.939 24346-25889/com.{mypackagename} I/OMXClient: Using client-side OMX mux.  
07-25 15:32:18.944 24346-25889/com.{mypackagename} E/OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.  
07-25 15:32:18.971 24346-25894/com.{mypackagename} I/OMXClient: Using client-side OMX mux.  
07-25 15:32:18.974 24346-25894/com.{mypackagename} E/OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.  
07-25 15:32:18.996 24346-25897/com.{mypackagename} I/OMXClient: Using client-side OMX mux.  
07-25 15:32:18.999 24346-25897/com.{mypackagename} E/OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.  
07-25 15:32:21.974 24346-25946/com.{mypackagename} I/OMXClient: Using client-side OMX mux.  
07-25 15:32:21.978 24346-25946/com.{mypackagename} E/OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.  
07-25 15:32:22.022 24346-25949/com.{mypackagename} I/OMXClient: Using client-side OMX mux.  
07-25 15:32:22.026 24346-25949/com.{mypackagename} E/OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.  
07-25 15:32:22.063 24346-25954/com.{mypackagename} I/OMXClient: Using client-side OMX mux.  
07-25 15:32:22.067 24346-25954/com.{mypackagename} E/OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.  
07-25 15:32:22.103 24346-25959/com.{mypackagename} I/OMXClient: Using client-side OMX mux.  
07-25 15:32:22.107 24346-25959/com.{mypackagename} E/OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.  
07-25 15:33:14.372 24346-26669/com.{mypackagename} I/OMXClient: Using client-side OMX mux.  
07-25 15:33:14.383 24346-26669/com.{mypackagename} E/OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.  
07-25 15:33:14.424 24346-26676/com.{mypackagename} I/OMXClient: Using client-side OMX mux.  
07-25 15:33:14.429 24346-26676/com.{mypackagename} E/OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.  
07-25 15:33:14.470 24346-26679/com.{mypackagename} I/OMXClient: Using client-side OMX mux.  
07-25 15:33:14.473 24346-26679/com.{mypackagename} E/OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.  
07-25 15:33:14.506 24346-26682/com.{mypackagename} I/OMXClient: Using client-side OMX mux.  
07-25 15:33:14.509 24346-26682/com.{mypackagename} E/OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.  
```

**Comment by ronocod** [comment] 2016-07-26 09:08
This seems to be caused by a duplicate decoder entry in the device's codec registry. You can see the duplicate entries [here](http://androidxref.com/6.0.1_r10/search?q=%22OMX.qcom.audio.decoder.aac%22&defs=&refs=&path=&hist=&project=abi&project=art&project=bionic&project=bootable&project=build&project=cts&project=dalvik&project=developers&project=development&project=device&project=docs&project=external&project=frameworks&project=hardware&project=libcore&project=libnativehelper&project=ndk&project=packages&project=pdk&project=platform_testing&project=prebuilts&project=sdk&project=system&project=tools) and the fixed that was merged into Cyanogenmod [here](http://review.cyanogenmod.org/#/c/122804/). 

Sounds should still be playing fine, you can check by sending a message from the messenger. Unless you're seeing any issues then I think it's safe to ignore this

**Comment by Amagi82** [comment] 2016-07-26 09:41
Understood. Thanks for looking into it. The sounds do play, so this is probably safe to close.

**Closed** 2016-07-26 09:45 UTC

**Comment by SanjayMallur** [comment] 2017-04-11 17:04
http://review.cyanogenmod.org/#/c/122804/ is not working...
