### ISSUE TITLE
Show notification instead of bubble (when app opened and intercom activity closed)

### ISSUE THREAD

**Issue by mariuspena** [intercom/intercom-android#481] opened 2018-02-09 17:09 UTC
Because of UX issues I do not need the in app bubble that shows every time I receive a message. So I hide it: Intercom.client().setInAppMessageVisibility(Intercom.Visibility.GONE)
I would rather use the notification in the system tray to show me the latest messages when they are sent.

## Version info
  - Intercom for Android version: 4+
  - Android OS version: 8.1.0
  - Android Device: Nexus 5x

## Expected behavior
app opened, intercom activity closed - I would want a flag that I can set so I can switch from the bubble to normal notifications in the system tray. yes it's a feature :)

## Actual behavior
app opened, intercom activity closed - the in app message bubble shows the messages I receive. 

## Steps to reproduce
 1. open app, open intercom, close intercom, remain in the app
 2. from the admin send a message to that user from step 1
 3. the bubble shows and displays the message I received in intercom

## Logs

**Comment by ronocod** [comment] 2018-02-12 10:17
Thanks for sending this in, as it's not a bug or an issue with the SDK I'll close this and note it as a feature request.

**Closed by ronocod** 2018-02-12 10:17 UTC

**Comment by mariuspena** [comment] 2018-02-12 10:22
thank you
