### ISSUE TITLE
android.os.NetworkOnMainThreadException in Okio

### ISSUE THREAD

**Issue by peterklima** [intercom/intercom-android#324] opened 2017-03-23 08:32 UTC
## Version info
  - Intercom for Android version: 3.1.1
  - Android OS version: 6 60%, 5 35%, 7 5%
  - Android Device: SM-G610F, Galaxy J7, Galaxy S6

## Expected behavior
No crash. 
## Actual behavior
Crashes because application attempts to perform a network operation on the main thread.
![screen shot 2017-03-23 at 09 29 55](https://cloud.githubusercontent.com/assets/1203988/24238652/57b45b54-0fab-11e7-8d99-bf60bf20e253.png)

## Logs
[log.txt](https://github.com/intercom/intercom-android/files/864055/log.txt)

**Comment by ronocod** [comment] 2017-03-23 09:31
If you look at the stack trace for your Exception, it looks like it's caused by your app code making a network call on the main thread using Retrofit and RxJava. You can avoid this my making your subscriber subscribe on the IO scheduler and observe the result on the main thread like this:
```java
.subscribeOn(Schedulers.io())
.observeOn(AndroidSchedulers.mainThread())
```
Closing this as it isn't being caused by our SDK.

**Closed by ronocod** 2017-03-23 09:31 UTC

**Comment by peterklima** [comment] 2017-03-30 13:20
@ronocod sorry to bother you, but how can you be sure? I am unable to find any stack trace entry related to specific app classes. How would you debug this issue? 
Additionally, I checked every .subscribeOn() - it is called either with Schedulers.io() or Schedulers.newThread(). Furthermore, .observeOn() is mainly called with AndroidSchedulers.mainThread() (when manipulating UI) or with Schedulers.io() as well.
Thank you for any help.

**Comment by ronocod** [comment] 2017-03-30 13:34
If you look at lines 1209-1221 in the log file you posted you can see that we use our own private version of OkHttp (`io.intercom.okhttp3`), and your crash came from the version of OkHttp that your app uses (`com.squareup.okhttp`). Our SDK has no access to the app's version of OkHttp, so the issue must be coming from somewhere else in your app.

I'm not sure what the cause is exactly, if the code I posted above doesn't fix it then it must be a different issue.
