### ISSUE TITLE
RuntimeException crash in intercom -  Could not dispatch event: class io.intercom.android.sdk.models.Events.ConversationEvent

### ISSUE THREAD

**Issue by manishkungwani** [intercom/intercom-android#86] opened 2015-06-03 13:23 UTC
Hi,
When using intercom v0.9.5, got this exception on the Play Store apk.
Please have a look at the Exception:

java.lang.RuntimeException: Could not dispatch event: class io.intercom.android.sdk.models.Events.ConversationEvent to handler [EventHandler public void io.intercom.android.sdk.conversation.ConversationFragment.conversationSuccess(io.intercom.android.sdk.models.Events.ConversationEvent)]: setSpan (0 ... 144) ends beyond length 138
at com.squareup.otto.Bus.throwRuntimeException(Bus.java:460)
at com.squareup.otto.Bus.dispatch(Bus.java:387)
at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:368)
at com.squareup.otto.Bus.post(Bus.java:337)
at io.intercom.android.sdk.api.MainThreadBus.post(MainThreadBus.java:22)
at io.intercom.android.sdk.api.CallbackHolder$5.success(CallbackHolder.java:83)
at io.intercom.android.sdk.api.CallbackHolder$5.success(CallbackHolder.java:81)
at retrofit.CallbackRunnable$1.run(CallbackRunnable.java:45)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
Caused by: java.lang.IndexOutOfBoundsException: setSpan (0 ... 144) ends beyond length 138
at android.text.SpannableStringInternal.checkRange(SpannableStringInternal.java:351)
at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:79)
at android.text.SpannableString.setSpan(SpannableString.java:46)
at io.intercom.android.sdk.blocks.UnorderedList.addUnorderedList(UnorderedList.java:61)
at io.intercom.android.blocks.BlockType$4.generateView(BlockType.java:25)
at io.intercom.android.blocks.Blocks.createBlocks(Blocks.java:32)
at io.intercom.android.sdk.conversation.BaseConversationFragment.createMessageUI(BaseConversationFragment.java:125)
at io.intercom.android.sdk.conversation.ConversationFragment.createConversationUI(ConversationFragment.java:572)
at io.intercom.android.sdk.conversation.ConversationFragment.setupWithConversation(ConversationFragment.java:512)
at io.intercom.android.sdk.conversation.ConversationFragment.conversationSuccess(ConversationFragment.java:362)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
at com.squareup.otto.Bus.dispatch(Bus.java:385)
... 14 more

**Comment by DaleCantwell** [comment] 2015-06-03 13:27
@manishkungwani thanks for reporting this issue. It is a duplicate of https://github.com/intercom/intercom-android/issues/85 the issue was resolved in 1.0.2.

**Closed by DaleCantwell** 2015-06-03 13:27 UTC

**Comment by manishkungwani** [comment] 2015-06-03 13:40
I apologize for reporting the same issue again. Sorry Dale.

**Comment by DaleCantwell** [comment] 2015-06-03 14:02
No problem at all, better safe than sorry.
