### ISSUE TITLE
cant register users after updating to 1.1.15

### ISSUE THREAD

**Issue by NammariMarkavip** [intercom/intercom-android#181] opened 2016-02-23 11:21 UTC
I can not register users after updating to sdk version 1.1.15 

log message 

Intercom-Android: ERROR: Failed to register or update user: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference

**Comment by harkin** [comment] 2016-03-04 16:17
This should be fixed in 1.1.16, let us know if you see any issues with that version :+1:

**Comment by NammariMarkavip** [comment] 2016-03-07 19:39
Its not fixed , I just tried version 1.1.16 and still the same issue

**Comment by harkin** [comment] 2016-03-08 14:54
@NammariMarkavip Hm, I'd thought this might be related to us updating Okhttp, not so sure of that anymore. I can't reproduce this error locally. Can you try running our [sample app](https://github.com/intercom/intercom-android/tree/master/samples/intercom-androidstudio-sample) and let me know if that works for you?

**Comment by samehgerges** [comment] 2016-03-11 13:15
we also still have this issue even after updating to 1.1.16. Our project has Retrofit 1.9.0, OKHttp 2.7.5 and Google play services 8.4.0 as dependencies as well

**Comment by ronocod** [comment] 2016-06-14 12:48
@samehgerges can you try version 1.1.21? This should be fixed in that version.

**Comment by DaleCantwell** [comment] 2016-07-08 14:35
@NammariMarkavip @samehgerges I'm to close out this issue, its fixed in version 1.1.21
Let us know if this occurs again in 1.1.21 and we will reopen.

**Closed by DaleCantwell** 2016-07-08 14:35 UTC
Labels: bug, Needs Info

**Comment by samehgerges** [comment] 2016-07-11 07:27
Thank you guys it's working
