### ISSUE TITLE
NPE on kitkat devices io.intercom.android.sdk.inbox.InboxFragment.displayEmptyView

### ISSUE THREAD

**Issue by hhoang** [intercom/intercom-android#292] opened 2016-11-21 21:29 UTC
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Android version: intercom-sdk:3.0.11
  - Android OS version: 4.4.2
  - Android Device: Gigabyte RCT6203W46

## Expected behavior
Handle messages without crashing

## Actual behavior
Crashes

## Steps to reproduce
 1. 
 2. 
 3. 

## Logs

[prod_issue_262_crash_58320e430264000127a0b85d2f85f374.txt](https://github.com/intercom/intercom-android/files/604816/prod_issue_262_crash_58320e430264000127a0b85d2f85f374.txt)

**Comment by ronocod** [comment] 2016-11-21 21:47
Duplicate of https://github.com/intercom/intercom-android/issues/282, fixed in version 3.0.12.

**Closed by ronocod** 2016-11-21 21:47 UTC
