### ISSUE TITLE
lang.java.OutOfMemoryError: (Could not allocate JNI Env) - okhttp3.ConnectionPool

### ISSUE THREAD

**Issue by noinlijin** [intercom/intercom-android#388] opened 2017-07-28 07:51 UTC
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Android version: 3.2.8
  - Android OS version:7.0
  - Android Device: Galaxy S6 SM-G920F

## Expected behavior
app crash
## Steps to reproduce
lang.java.OutOfMemoryError: (Could not allocate JNI Env)
at lang.java.Thread.nativeCreate(Native Method)
at lang.java.Thread.start(Thread.java:731)
at concurrent.util.java.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:941)
at concurrent.util.java.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1359)
at okhttp3.intercom.io.ConnectionPool.put(149)
at okhttp3.intercom.io.OkHttpClient$1.put(158)
at connection.internal.okhttp3.intercom.io.StreamAllocation.findConnection(192)
at connection.internal.okhttp3.intercom.io.StreamAllocation.findHealthyConnection(121)
at connection.internal.okhttp3.intercom.io.StreamAllocation.newStream(100)
at connection.internal.okhttp3.intercom.io.ConnectInterceptor.intercept(42)
at http.internal.okhttp3.intercom.io.RealInterceptorChain.proceed(92)
at http.internal.okhttp3.intercom.io.RealInterceptorChain.proceed(67)
at cache.internal.okhttp3.intercom.io.CacheInterceptor.intercept(93)
at http.internal.okhttp3.intercom.io.RealInterceptorChain.proceed(92)
at http.internal.okhttp3.intercom.io.RealInterceptorChain.proceed(67)
at http.internal.okhttp3.intercom.io.BridgeInterceptor.intercept(93)
at http.internal.okhttp3.intercom.io.RealInterceptorChain.proceed(92)
at http.internal.okhttp3.intercom.io.RetryAndFollowUpInterceptor.intercept(120)
at http.internal.okhttp3.intercom.io.RealInterceptorChain.proceed(92)
at http.internal.okhttp3.intercom.io.RealInterceptorChain.proceed(67)
at api.sdk.android.intercom.io.ShutdownInterceptor.intercept(35)
at http.internal.okhttp3.intercom.io.RealInterceptorChain.proceed(92)
at http.internal.okhttp3.intercom.io.RealInterceptorChain.proceed(67)
at api.sdk.android.intercom.io.RetryInterceptor.intercept(21)
at http.internal.okhttp3.intercom.io.RealInterceptorChain.proceed(92)
at http.internal.okhttp3.intercom.io.RealInterceptorChain.proceed(67)
at api.sdk.android.intercom.io.UserIdentityInterceptor.intercept(29)
at http.internal.okhttp3.intercom.io.RealInterceptorChain.proceed(92)
at http.internal.okhttp3.intercom.io.RealInterceptorChain.proceed(67)
at okhttp3.intercom.io.RealCall.getResponseWithInterceptorChain(179)
at okhttp3.intercom.io.RealCall$AsyncCall.execute(129)
at internal.okhttp3.intercom.io.NamedRunnable.run(32)
at concurrent.util.java.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at concurrent.util.java.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at lang.java.Thread.run(Thread.java:762)

## Logs

This is a crash report I received in production, first time I've ever seen it, no steps to reproduce
because I didn't invoke the crash.

**Comment by littlefoxvpn** [comment] 2017-09-06 10:54
I meet like the same crash    
```
Fatal Exception: java.lang.OutOfMemoryError: Could not allocate JNI Env
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:921)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
       at io.intercom.okhttp3.ConnectionPool.put(Unknown Source)
       at io.intercom.okhttp3.OkHttpClient$1.put(Unknown Source)
       at io.intercom.okhttp3.internal.connection.StreamAllocation.findConnection(Unknown Source)
       at io.intercom.okhttp3.internal.connection.StreamAllocation.findHealthyConnection(Unknown Source)
       at io.intercom.okhttp3.internal.connection.StreamAllocation.newStream(Unknown Source)
       at io.intercom.okhttp3.internal.connection.ConnectInterceptor.intercept(Unknown Source)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source)
       at io.intercom.okhttp3.internal.cache.CacheInterceptor.intercept(Unknown Source)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source)
       at io.intercom.okhttp3.internal.http.BridgeInterceptor.intercept(Unknown Source)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source)
       at io.intercom.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(Unknown Source)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source)
       at io.intercom.android.sdk.api.ShutdownInterceptor.intercept(Unknown Source)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source)
       at io.intercom.android.sdk.api.RetryInterceptor.intercept(Unknown Source)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source)
       at io.intercom.android.sdk.api.UserIdentityInterceptor.intercept(Unknown Source)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source)
       at io.intercom.okhttp3.RealCall.getResponseWithInterceptorChain(Unknown Source)
       at io.intercom.okhttp3.RealCall$AsyncCall.execute(Unknown Source)
       at io.intercom.okhttp3.internal.NamedRunnable.run(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

```

**Comment by ronocod** [comment] 2017-09-08 12:49
This looks like an OutOfMemoryError caused by us trying to open a network connection while your app is out of memory. There's nothing we can do to protect against this, it's likely caused by high memory usage in your app. Closing this as it's not an issue with our SDK.

**Closed by ronocod** 2017-09-08 12:49 UTC
