### ISSUE TITLE
Out of Memory error in GalleryLightBoxActivity

### ISSUE THREAD

**Issue by Amagi82** [intercom/intercom-android#387] opened 2017-07-25 19:43 UTC
## Version info
  - Intercom for Android version: 3.2.6
  - Android OS version: API 25, API 23
  - Android Device: Pixel XL and Samsung SM-J700T1

I've had this happen 7 times in production with the specific devices mentioned above. Logs indicate they were all in GalleryLightBoxActivity when the crash occurred.

## Logs

```
OutOfMemoryError - VMRuntime.newNonMovableArray
Exception java.lang.OutOfMemoryError: Failed to allocate a 15539376 byte allocation with 8115680 free bytes and 7MB until OOM
dalvik.system.VMRuntime.newNonMovableArray (VMRuntime.java)
android.graphics.Bitmap.nativeCreate (Bitmap.java)
android.graphics.Bitmap.createBitmap (Bitmap.java:879)
android.graphics.Bitmap.createBitmap (Bitmap.java:856)
android.graphics.Bitmap.createBitmap (Bitmap.java:823)
com.intercom.input.gallery.AnnotatedImageView.createCanvasWithSameBoundsAsRenderedDrawable (AnnotatedImageView.java)
com.intercom.input.gallery.AnnotatedImageView.drawPaths (AnnotatedImageView.java)
<OR>.clear (AnnotatedImageView.java)
<OR>.access$000 (AnnotatedImageView.java)
com.intercom.input.gallery.AnnotatedImageView$1.run (AnnotatedImageView.java)
android.os.Handler.handleCallback (Handler.java:751)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6121)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:889)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:779)
```

**Comment by ronocod** [comment] 2017-08-08 16:17
Duplicate of https://github.com/intercom/intercom-android/issues/371, we're working on a fix.

**Closed by ronocod** 2017-08-08 16:17 UTC
