### ISSUE TITLE
NoClassDefFoundError Twig

### ISSUE THREAD

**Issue by swordark** [intercom/intercom-android#438] opened 2017-10-12 13:29 UTC
I ve been using intercom for 1 year and suddenly i started to get error on some of the API level 22 devices. (Emulator Nexus 5, Samsung SM-G531F etc.) I've tried similar issues solutions but they didnt work for me. I've already implement multidex support and checked for conflicts with other libraries. But i couldnt find anything wrong. 

## Version info
  - Intercom for Android version: 4+
  - Android OS version: 5.1.1 
  - Android Device: Emulator Nexus 5 

## Expected behavior
Normal start
## Actual behavior
Crash on start
## Steps to reproduce
 1. On Emulator Nexus 5 with API level 22 just try to run application

## Logs

```
 Process: com.nomad.basefy, PID: 15821
                                                                  java.lang.NoClassDefFoundError: Failed resolution of: Lio/intercom/android/sdk/twig/Twig;
                                                                      at io.intercom.android.sdk.logger.LumberMill.<clinit>(LumberMill.java:11)
                                                                      at io.intercom.android.sdk.logger.LumberMill.getLogger(LumberMill.java:16)
                                                                      at io.intercom.android.sdk.LateInitializationPreparer.<init>(LateInitializationPreparer.java:21)
                                                                      at io.intercom.android.sdk.LateInitializationPreparer.getInstance(LateInitializationPreparer.java:29)
                                                                      at io.intercom.android.sdk.IntercomInitializeContentProvider.onCreate(IntercomInitializeContentProvider.java:18)
                                                                      at android.content.ContentProvider.attachInfo(ContentProvider.java:1696)
                                                                      at android.content.ContentProvider.attachInfo(ContentProvider.java:1671)
                                                                      at android.app.ActivityThread.installProvider(ActivityThread.java:4999)
                                                                      at android.app.ActivityThread.installContentProviders(ActivityThread.java:4594)
                                                                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4534)
                                                                      at android.app.ActivityThread.access$1500(ActivityThread.java:151)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:135)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                   Caused by: java.lang.ClassNotFoundException: Didn't find class "io.intercom.android.sdk.twig.Twig" on path: DexPathList[[zip file "/data/app/com.nomad.basefy-2/base.apk", zip file "/data/app/com.nomad.basefy-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.nomad.basefy-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.nomad.basefy-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.nomad.basefy-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.nomad.basefy-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.nomad.basefy-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.nomad.basefy-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.nomad.basefy-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.nomad.basefy-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.nomad.basefy-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.nomad.basefy-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.nomad.basefy-2/lib/x86, /vendor/lib, /system/lib]]
```

**Comment by DaleCantwell** [comment] 2017-10-12 14:05
Hi @swordark,

We have seen this issue pop up a couple times.

https://github.com/intercom/intercom-android/issues/382
https://github.com/intercom/intercom-android/issues/404

Can you post the versions you have for:

* compileSdkVersion
* buildToolsVersion
* The Multidex Support Library
* The Android Gradle plugin

Could I get you to run `./gradlew dependencies` as well and post the results here (or if you would rather not share your dependancy tree publicly you use our messenger at www.intercom.com)

This could be caused by the app and our SDK having some variance in build tools or library versions.

**Comment by swordark** [comment] 2017-10-12 14:25
I've already checked those issues, but couldnt get a solution. 

compileSdkVersion 25
buildToolsVersion 25.0.0
Multidex Support lib 1.0.1
Gradle version 2.3.3

I'll share dependancy tree via messenger. I did clean build many times as well.  :)

Btw thanks for fast response.

**Comment by DaleCantwell** [comment] 2017-10-12 14:53
Could you try updating to the versions below and rebuild? 

```
compileSdkVersion 26
buildToolsVersion 26.0.1
```

**Comment by swordark** [comment] 2017-10-13 06:13
I tried with updated versions. 
But to avoid possible conflictions i am using intercom gradle as below. Can this be related? 

`    compile ("io.intercom.android:intercom-sdk-base:4.+"){

        transitive = true;

    }`

**Comment by swordark** [comment] 2017-10-13 11:38
Still i couldnt find any solution. I've updated all support libraries and buildtools version compilesdk version etc. I did many clean builds. But still i have the same problem on 5.1.1 devices. And unfortunately, my client is trying to test my app on 5.1.1 device. :)

**Comment by ronocod** [comment] 2017-11-02 15:27
@swordark did you get this working? Instant Run may be the issue here, have you tried with that disabled?

**Comment by ronocod** [comment] 2017-12-01 14:41
This is being caused by the build setup for this specific app, we can't fix this by changing the SDK. Happy to continue providing support but I'll close this as an issue.

**Closed by ronocod** 2017-12-01 14:41 UTC
