### ISSUE TITLE
RuntimeException - ActivityThread.performLaunchActivity help

### ISSUE THREAD

**Issue by vahidlazio** [intercom/intercom-android#295] opened 2016-12-05 15:20 UTC
This exception happened more than 1K in a week.

## Version info
  - Intercom for Android version: 3.0.11
  - Android OS version:  4.4.4
  - Android Device:
Manufacturer: Samsung
Model: GT-I9060I
Board: Sc7730s
Android API: 19
Android OS: 4.4.4
Brand: Samsung
RAM: 952MB
Available on disk: —
Orientation: Portrait
Proximity to user: —
## Logs

Exception java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hungerstation.android.web/io.intercom.android.sdk.activities.IntercomMessengerActivity}: java.lang.NullPointerException
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2429)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2493)
android.app.ActivityThread.access$800 (ActivityThread.java:166)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1283)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:136)
android.app.ActivityThread.main (ActivityThread.java:5584)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1268)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1084)
dalvik.system.NativeStart.main (NativeStart.java)
arrow_drop_down
Caused by java.lang.NullPointerException:
io.intercom.android.sdk.inbox.InboxFragment.displayEmptyView ()
io.intercom.android.sdk.inbox.InboxFragment.onStateChange ()
io.intercom.android.sdk.inbox.InboxFragment.onStateChange ()
io.intercom.android.sdk.utilities.ChangeSubscriber.onStateChange ()
io.intercom.android.sdk.store.Store.subscribe ()
io.intercom.android.sdk.store.Store.subscribeToChanges ()
io.intercom.android.sdk.inbox.InboxFragment.onCreate ()
android.support.v4.app.Fragment.performCreate ()
android.support.v4.app.v.a ()
android.support.v4.app.v.a ()
android.support.v4.app.l.run ()
android.support.v4.app.v.f ()
android.support.v4.app.s.o ()
android.support.v4.app.q.onStart ()
android.support.v7.a.e.onStart ()
android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1178)
android.app.Activity.performStart (Activity.java:5452)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2402)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2493)
android.app.ActivityThread.access$800 (ActivityThread.java:166)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1283)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:136)
android.app.ActivityThread.main (ActivityThread.java:5584)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1268)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1084)
dalvik.system.NativeStart.main (NativeStart.java)

**Comment by ronocod** [comment] 2016-12-05 23:13
This is a duplicate of https://github.com/intercom/intercom-android/issues/282, it was fixed in 3.0.12.

**Closed by ronocod** 2016-12-05 23:13 UTC
