### ISSUE TITLE
After close the intercom messenger, the app reset the language of the UI

### ISSUE THREAD

**Issue by leandono** [intercom/intercom-android#223] opened 2016-07-25 17:35 UTC
## Version info
  - Intercom for Android version: 3.0.1
  - Android OS version: 6.0
  - Android Device: Motorola G2

## Expected behavior
Keep the preferred language of the app UI (based on the language preference of the OS)
## Actual behavior
After open and close the Intercom messenger, the app reset the language of the UI for the default one.
## Steps to reproduce
 1. Use the app with a different language of the default, changing the language preference of the OS. For example, if the preference of the OS is portuguese, the app will load with the strings.xml of the `values-pt-rBR` folder.
 2. Open the messenger using `Intercom.client().displayMessenger();`
 3. Close the messenger UI and reload an activity. The activity start using the default language of the app (from the `values` folder) and not from `values-pt-rBR`
 4. To start using the correct language, the app needs to be closed and opened again.

I saw that in the new version of the SDK you added the support of localizations, maybe is an issue related by that? The issue also happens in another versions of android.

**Comment by ronocod** [comment] 2016-07-25 18:01
Yes, I imagine this is related to localization. Investigating it now.

**Comment by ronocod** [comment] 2016-07-25 19:16
Found the cause, working on a fix now. We'll ship 3.0.2 when the fix is merged.

**Comment by ronocod** [comment] 2016-07-26 13:01
3.0.2 is out and contains the fix for this.

**Closed by ronocod** 2016-07-26 13:01 UTC

**Comment by leandono** [comment] 2016-07-26 17:34
Great, thanks!
