### ISSUE TITLE
conversation title display bug

### ISSUE THREAD

**Issue by pengyuan1990** [intercom/intercom-android#380] opened 2017-07-18 02:02 UTC
## Version info
  - Intercom for Android version: v3.2.8
  - Android OS version: any
  - Android Device: any

## Expected behavior
 title and user state overlap
## Steps to reproduce
 1. begin a  conversation

## Logs
![image](https://user-images.githubusercontent.com/15941999/28297355-05dba3b8-6ba0-11e7-96cb-4074fde07d67.png)

**Comment by DaleCantwell** [comment] 2017-07-18 09:22
Thanks for reporting this, closing as a dupe of https://github.com/intercom/intercom-android/issues/378

**Closed by DaleCantwell** 2017-07-18 09:22 UTC
