### ISSUE TITLE
Crash at TeammateProfileToolbarBehavior.java line 141

### ISSUE THREAD

**Issue by chuyeoh** [intercom/intercom-android#267] opened 2016-10-03 03:50 UTC
## Version info
  - Intercom for Android version: 3.0.5
  - Android OS version: 4.1.2
  - Android Device: Acer, Samsung

## Logs
Fatal Exception: java.lang.NoSuchMethodError: android.view.ViewGroup.isInLayout
       at io.intercom.android.sdk.profile.TeammateProfileToolbarBehavior.onOffsetChanged(TeammateProfileToolbarBehavior.java:141)
       at android.support.design.widget.AppBarLayout.dispatchOffsetUpdates(AppBarLayout.java:464)
       at android.support.design.widget.AppBarLayout.access$800(AppBarLayout.java:104)
       at android.support.design.widget.AppBarLayout$Behavior.setHeaderTopBottomOffset(AppBarLayout.java:1149)
       at android.support.design.widget.AppBarLayout$Behavior.setHeaderTopBottomOffset(AppBarLayout.java:755)
       at android.support.design.widget.HeaderBehavior.setHeaderTopBottomOffset(HeaderBehavior.java:194)
       at android.support.design.widget.AppBarLayout$Behavior.onLayoutChild(AppBarLayout.java:1048)
       at android.support.design.widget.AppBarLayout$Behavior.onLayoutChild(AppBarLayout.java:755)
       at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:852)
       at android.view.View.layout(View.java:13846)
       at android.view.ViewGroup.layout(ViewGroup.java:4466)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:948)
       at android.view.View.layout(View.java:13846)
       at android.view.ViewGroup.layout(ViewGroup.java:4466)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:13846)
       at android.view.ViewGroup.layout(ViewGroup.java:4466)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
       at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1638)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1422)
       at android.view.View.layout(View.java:13846)
       at android.view.ViewGroup.layout(ViewGroup.java:4466)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:13846)
       at android.view.ViewGroup.layout(ViewGroup.java:4466)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
       at android.view.View.layout(View.java:13846)
       at android.view.ViewGroup.layout(ViewGroup.java:4466)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:13846)
       at android.view.ViewGroup.layout(ViewGroup.java:4466)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:13846)
       at android.view.ViewGroup.layout(ViewGroup.java:4466)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:13846)
       at android.view.ViewGroup.layout(ViewGroup.java:4466)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2156)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1914)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1134)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4616)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:747)
       at android.view.Choreographer.doCallbacks(Choreographer.java:567)
       at android.view.Choreographer.doFrame(Choreographer.java:536)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:733)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:153)
       at android.app.ActivityThread.main(ActivityThread.java:4987)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by ronocod** [comment] 2016-10-03 09:01
Duplicate of https://github.com/intercom/intercom-android/issues/252, fixed in 3.0.6

**Closed by ronocod** 2016-10-03 09:01 UTC
