### ISSUE TITLE
java.lang.OutOfMemoryError: Failed to allocate a 10304112 byte allocation with 9296101 free bytes and 8MB until OOM 	

### ISSUE THREAD

**Issue by noinlijin** [intercom/intercom-android#390] opened 2017-07-29 02:33 UTC
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Android version:3.2.8
  - Android OS version:6.0.1
  - Android Device:MI 5s 

## Expected behavior
The solution is downloaded from the cloud test platform，the language is Chinese, I copied and pasted

## Steps to reproduce
详细说明
问题分析：

OutOfMemoryError是在当程序需要请求一块内存，而java虚拟机进行垃圾回收机制GC后无法再提供要求的内存时抛出此异常。

解决方案：

OutOfMemoryError是在当程序需要请求一块内存，而java虚拟机进行垃圾回收机制GC后无法再提供要求的内存时抛出此类异常，程序已经占用的内存到达系统限制的应用内存上线无法再申请到所需的内存空间。需要重点检查代码中是否有死循环或递归调用。检查是否在循环重复产生占用大内存的新对象。是否有一次获得大量数据的查询存到内存中，应当尽量用分页的方式查询。是否List、Map等集合对象使用后未清除，而集合对象有对对象的引用导致对象不能被GC回收，是否有内存泄露等。建议使用深度性能测试检测内存泄漏等问题。

代码示例：

    // 在循环外初始化大对象list并在循环内重复使用，并清空集合类、置null
    List list=new ArrayList<Object>();
    for(Object tmp:otherList){
      // to do something
    } 
    list.clear();
    list=null;
参考文献：

1.https://developer.android.com/reference/java/lang/OutOfMemoryError.html

2.https://source.android.com/compatibility/android-cdd.html#7_6_memory_and_storage （安卓系统对程序所使用内存的最大值限制，参见3.7节的表格，或直接参考文献3)

3.https://drive.google.com/file/d/0B7Vx1OvzrLa3Y0R0X1BZbUpicGc/view?usp=sharing（安卓系统对内存最大值限制）

## Logs
java.lang.OutOfMemoryError: Failed to allocate a 10304112 byte allocation with 9296101 free bytes and 8MB until OOM 							
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method) 							
	at android.graphics.Bitmap.nativeCreate(Native Method) 							
	at android.graphics.Bitmap.createBitmap(Bitmap.java:812) 							
	at android.graphics.Bitmap.createBitmap(Bitmap.java:789) 							
	at android.graphics.Bitmap.createBitmap(Bitmap.java:756) 							
	at com.intercom.input.gallery.AnnotatedImageView.d(SourceFile:129) 							
	at com.intercom.input.gallery.AnnotatedImageView.a(SourceFile:21) 							
	at com.intercom.input.gallery.AnnotatedImageView$1.run(SourceFile:87) 							
	at android.os.Handler.handleCallback(Handler.java:739)  							
	at android.os.Handler.dispatchMessage(Handler.java:95) 							
	at android.os.Looper.loop(Looper.java:135) 							
	at android.app.ActivityThread.main(ActivityThread.java:5400) 							
	at java.lang.reflect.Method.invoke(Native Method) 							
	at java.lang.reflect.Method.invoke(Method.java:372) 							
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037) 							
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by noinlijin** [comment] 2017-08-03 05:40
![image](https://user-images.githubusercontent.com/3073370/28907524-411f78a6-7851-11e7-8216-5664ae614d35.png)    
![image](https://user-images.githubusercontent.com/3073370/28907533-48d2e74a-7851-11e7-8c64-185abe12c061.png)

**Comment by DaleCantwell** [comment] 2017-08-04 10:53
Hi @noinlijin we are looking into this issue. Thank you for reporting it. I will update this issue once we have a fix.
Thanks,
Dale

**Comment by skylerwshaw** [comment] 2017-08-08 12:59
@noinlijin What is your crash reporting tool? How frequently are you seeing this issue? How many different devices?

**Comment by ronocod** [comment] 2017-08-08 16:17
This is a duplicate of https://github.com/intercom/intercom-android/issues/371. We're working on a fix for this now.

**Closed by ronocod** 2017-08-08 16:17 UTC

**Comment by ronocod** [comment] 2017-11-14 10:09
`android:largeHeap="true"` is generally a bad idea, it doesn't actually fix the problem, it just allows your app to take up more memory before crashing.

We disabled the logic that caused this, so we haven't needed to fix it properly yet, but the fix is to create smaller Bitmap objects that are not too big to fit in memory. You can find more information here: https://developer.android.com/topic/performance/graphics/load-bitmap.html
