### ISSUE TITLE
NullPointerException on adding old image from Google Photos

### ISSUE THREAD

**Issue by twoznica** [intercom/intercom-android#193] opened 2016-04-20 11:22 UTC
## Version info
  - Intercom for Android version: 1.1.17
  - Android OS version: 6.0.1
  - Android Device: Nexus 5

## Expected behavior
User should be able to add any photo from Google Photos

## Actual behavior
App crashes.
It's actually Google Photos strange behaviour, as I did encounter this in different app, but is not handled on Intecom side properly nonetheless.

## Steps to reproduce
 1. Upload a photo to Google Photos.(do not take it using camera)
 2. Do not open this photo on testing device. (as it'd download it to the device).
 3. In intercom add an attachment from Google Photos and select previously uploaded photo.

## Logs

`java.lang.RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$3.done(AsyncTask.java:309)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
    at io.intercom.android.sdk.attachments.AttachmentData.&lt;init&gt;(AttachmentData.java:39)
    at io.intercom.android.sdk.attachments.AttachmentPresenter$LoadFileTask.doInBackground(AttachmentPresenter.java:87)
    at io.intercom.android.sdk.attachments.AttachmentPresenter$LoadFileTask.doInBackground(AttachmentPresenter.java:84)
    at android.os.AsyncTask$2.call(AsyncTask.java:295)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    ... 4 more`

**Comment by harkin** [comment] 2016-04-22 12:25
Thanks for letting us know about this @twoznica 

We have come across this before and actually catch that exception when it's thrown. Is this a crash that you can reproduce yourself? I'm testing here with the same device, OS and library version and can't reproduce it; the exception is correctly being caught and we're displaying an error.

**Comment by DaleCantwell** [comment] 2016-07-21 14:42
Hi @twoznica,
We just released 3.0.0 🎉  https://github.com/intercom/intercom-android/releases/tag/3.0.0
We haven't been able to reproduce this issue. I'm going to close it for now, if you see it in 3.0.0 could you let us know an we will reopen and investigate agin.
Thanks,
-Dale

**Closed by DaleCantwell** 2016-07-21 14:42 UTC
