### ISSUE TITLE
NPE in OkHttp/Okio Code

### ISSUE THREAD

**Issue by hanspeide** [intercom/intercom-android#329] opened 2017-04-03 11:27 UTC
Crashlytics crash reports shows a NPE occuring in OkHttp/Okio.

## Version info
  - Intercom for Android version: 3.0.21
  - Android OS version: 7
  - Android Device: Samsung Galaxy S7 Edge

## Expected behavior
No NPE

## Actual behavior
NPE

## Steps to reproduce
Unknown

## Logs

```
#0. Crashed: OkHttp Dispatcher: 0 0 0x0000000000000000
       at io.intercom.okio.Segment.pop(Segment.java:85)
       at io.intercom.okio.Buffer.skip(Buffer.java:820)
       at io.intercom.okio.RealBufferedSource.skip(RealBufferedSource.java:308)
       at io.intercom.okhttp3.internal.ws.WebSocketReader$FramedMessageSource.close(WebSocketReader.java:309)
       at io.intercom.okio.RealBufferedSource.close(RealBufferedSource.java:434)
       at io.intercom.okhttp3.internal.Util.closeQuietly(Util.java:88)
       at io.intercom.okhttp3.ResponseBody.bytes(ResponseBody.java:130)
       at io.intercom.okhttp3.ResponseBody.string(ResponseBody.java:154)
       at io.intercom.android.sdk.nexus.NexusSocket.onMessage(NexusSocket.java:191)
       at io.intercom.okhttp3.internal.ws.RealWebSocket$1.onMessage(RealWebSocket.java:62)
       at io.intercom.okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:242)
       at io.intercom.okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:108)
       at io.intercom.okhttp3.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97)
       at io.intercom.okhttp3.ws.WebSocketCall.createWebSocket(WebSocketCall.java:152)
       at io.intercom.okhttp3.ws.WebSocketCall.access$000(WebSocketCall.java:41)
       at io.intercom.okhttp3.ws.WebSocketCall$1.onResponse(WebSocketCall.java:97)
       at io.intercom.okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)
       at io.intercom.okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)

--

Fatal Exception: java.lang.NullPointerException: Attempt to write to field 'io.intercom.a.p io.intercom.a.p.f' on a null object reference
       at io.intercom.okio.Segment.pop(Segment.java:85)
       at io.intercom.okio.Buffer.skip(Buffer.java:820)
       at io.intercom.okio.RealBufferedSource.skip(RealBufferedSource.java:308)
       at io.intercom.okhttp3.internal.ws.WebSocketReader$FramedMessageSource.close(WebSocketReader.java:309)
       at io.intercom.okio.RealBufferedSource.close(RealBufferedSource.java:434)
       at io.intercom.okhttp3.internal.Util.closeQuietly(Util.java:88)
       at io.intercom.okhttp3.ResponseBody.bytes(ResponseBody.java:130)
       at io.intercom.okhttp3.ResponseBody.string(ResponseBody.java:154)
       at io.intercom.android.sdk.nexus.NexusSocket.onMessage(NexusSocket.java:191)
       at io.intercom.okhttp3.internal.ws.RealWebSocket$1.onMessage(RealWebSocket.java:62)
       at io.intercom.okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:242)
       at io.intercom.okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:108)
       at io.intercom.okhttp3.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97)
       at io.intercom.okhttp3.ws.WebSocketCall.createWebSocket(WebSocketCall.java:152)
       at io.intercom.okhttp3.ws.WebSocketCall.access$000(WebSocketCall.java:41)
       at io.intercom.okhttp3.ws.WebSocketCall$1.onResponse(WebSocketCall.java:97)
       at io.intercom.okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)
       at io.intercom.okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)

#0. Crashed: OkHttp Dispatcher: 0 0 0x0000000000000000
       at io.intercom.okio.Segment.pop(Segment.java:85)
       at io.intercom.okio.Buffer.skip(Buffer.java:820)
       at io.intercom.okio.RealBufferedSource.skip(RealBufferedSource.java:308)
       at io.intercom.okhttp3.internal.ws.WebSocketReader$FramedMessageSource.close(WebSocketReader.java:309)
       at io.intercom.okio.RealBufferedSource.close(RealBufferedSource.java:434)
       at io.intercom.okhttp3.internal.Util.closeQuietly(Util.java:88)
       at io.intercom.okhttp3.ResponseBody.bytes(ResponseBody.java:130)
       at io.intercom.okhttp3.ResponseBody.string(ResponseBody.java:154)
       at io.intercom.android.sdk.nexus.NexusSocket.onMessage(NexusSocket.java:191)
       at io.intercom.okhttp3.internal.ws.RealWebSocket$1.onMessage(RealWebSocket.java:62)
       at io.intercom.okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:242)
       at io.intercom.okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:108)
       at io.intercom.okhttp3.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97)
       at io.intercom.okhttp3.ws.WebSocketCall.createWebSocket(WebSocketCall.java:152)
       at io.intercom.okhttp3.ws.WebSocketCall.access$000(WebSocketCall.java:41)
       at io.intercom.okhttp3.ws.WebSocketCall$1.onResponse(WebSocketCall.java:97)
       at io.intercom.okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)
       at io.intercom.okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)
```

**Comment by ronocod** [comment] 2017-04-03 15:17
Investigating this now, is it happening on many devices?

**Comment by hanspeide** [comment] 2017-04-03 16:49
Newly released app, so just one device as of now.

Note that I was using version 3.0.21 (updating to latest now), so for all I know it might be fixed.

**Comment by znupy** [comment] 2017-04-04 07:13
https://github.com/intercom/intercom-android/issues/314

**Comment by ronocod** [comment] 2017-04-04 09:38
Ah yes, this is a dupe of #314, will close this and re-open that

**Closed by ronocod** 2017-04-04 09:38 UTC
