### ISSUE TITLE
lang.java.IllegalStateException: (Fragment GifInputFragment{759552e} not attached to Activity)

### ISSUE THREAD

**Issue by noinlijin** [intercom/intercom-android#389] opened 2017-07-28 07:54 UTC
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Android version:3.2.8
  - Android OS version:6.0.1
  - Android Device: Grand Prime Plus SM-G532G

## Expected behavior
app crash
## Steps to reproduce
lang.java.IllegalStateException: (Fragment GifInputFragment{759552e} not attached to Activity)
at app.v4.support.android.Fragment.getResources(646)
at a.bls.showErrorScreen(294)
at a.bls$1.a(83)
at galleryinput.composer.conversation.sdk.android.intercom.io.GifInputDataSource$1.onFailure(69)
at retrofit2.intercom.io.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$2.run(77)
at os.android.Handler.handleCallback(Handler.java:739)
at os.android.Handler.dispatchMessage(Handler.java:95)
at os.android.Looper.loop(Looper.java:148)
at app.android.ActivityThread.main(ActivityThread.java:7406)
at reflect.lang.java.Method.invoke(Native Method)
at os.internal.android.com.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at os.internal.android.com.ZygoteInit.main(ZygoteInit.java:1120)

## Logs
This is a crash report I received in production, first time I've ever seen it, no steps to reproduce
because I didn't invoke the crash.

**Comment by ronocod** [comment] 2017-08-08 13:50
Duplicate of https://github.com/intercom/intercom-android/issues/384, fixed in 3.2.9.

**Closed by ronocod** 2017-08-08 13:50 UTC
