### ISSUE TITLE
Update the readme.md for proguard rules

### ISSUE THREAD

**Issue by PaNaVTEC** [intercom/intercom-android#42] opened 2015-02-19 09:46 UTC
actually i'm using this 2:

```
-keep class intercom.** { *; }
-keep class io.intercom.** { *; }
```

I think I don't need more.

**Comment by DaleCantwell** [comment] 2015-03-24 13:39
For version 0.9.0 we use `consumerProguardFiles` so you shouldn't need to add the yourself anymore.

**Comment by liorry** [comment] 2015-10-25 09:27
That is actually not true. I'm using 1.1.8 and the project will build successfully but won't run unless you add these to your proguard file:
<pre><code>
-dontwarn intercom.**
-dontwarn io.intercom.**
</code></pre>

**Comment by harkin** [comment] 2015-10-25 10:00
Thanks for the heads up @liorry, we'll look into this next week

**Comment by harkin** [comment] 2015-10-27 10:53
@liorry I'm not able to reproduce that. I've made a new app, included the library and turned proguard on for debug builds and deployed it to my phone, it runs successfully. Could you give more details?

**Comment by harkin** [comment] 2015-11-16 10:25
Gonna close this one out, will reopen if I get more details about what was giving warnings

**Closed by harkin** 2015-11-16 10:25 UTC
Labels: Needs Info
