### ISSUE TITLE
displayConversationsList() crashes on android KitKat

### ISSUE THREAD

**Issue by pundroid** [intercom/intercom-android#283] opened 2016-11-10 08:25 UTC
conversations list in intercom crashes upon launch only on Android 4.+, behaves normally on Android 5.+, 6.+, and also 7.+. Other screens such as message composer are able to run normally, except conversations list.

## Version info
  - Intercom for Android version:  'io.intercom.android:intercom-sdk:3.+'
  - Android OS version: android KitKat, 4.4.2, 4.3, 4.4.4
  - Android Device: Android Studio emulator on API19, Galaxy S3

## Expected behavior
Display conversation lists as usual

## Actual behavior
Intercom crashes when calling Intercom.client().displayConversationsList();
Calling both Intercom.client().displayMessageComposer() or Intercom.client().displayMessenger(); on the other hand intercom behaves as expected.

## Steps to reproduce
 1. Create new android project
 2. Setup intercom as instructed 
 3. call displayConversationsList()

## Logs
[crash_log.txt](https://github.com/intercom/intercom-android/files/582805/crash_log.txt)

**Comment by ronocod** [comment] 2016-11-10 10:05
Duplicate of https://github.com/intercom/intercom-android/issues/282, we'll release a fix for this today.

**Closed by ronocod** 2016-11-10 10:05 UTC
