### ISSUE TITLE
java.lang.OutOfMemoryError:io.intercom.okhttp3.Dispatcher.enqueue

### ISSUE THREAD

**Issue by noinlijin** [intercom/intercom-android#399] opened 2017-08-12 01:04 UTC
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Android version:4.0.1
  - Android OS version:4.4
  - Android Device: Samsung Galaxy Core Prime (core33g), 1024MB RAM

## Expected behavior
this crash appear in google play crash log, covered intercom version of 3.2.6-4.0.1 ,like this issue https://github.com/intercom/intercom-android/issues/393, I am not sure they are the them 

## Steps to reproduce
 1. 
 2. 
 3. 

## Logs
![image](https://user-images.githubusercontent.com/3073370/29236389-90b4ec24-7f3c-11e7-8120-591460b70b4e.png)

**Comment by skylerwshaw** [comment] 2017-08-12 09:43
@noinlijin You have reported OutOfMemory errors across several issues. Have you inspected your application for heavy memory use or profiled any potential memory leaks? If your application is already has memory problems, launching Intercom can make a crash occur since the SDK is unable to use the application memory space without hitting the limit.

**Comment by noinlijin** [comment] 2017-08-15 00:32
intercom version from 3.2.6-4.0.1 this crash is aways here,

this crash is from Crash log collection platform flurry,There are obvious intercom error messages

![image](https://user-images.githubusercontent.com/3073370/29297525-2a92d6ea-8194-11e7-95b0-6e8df7e9542a.png)


```
ISSUE STACK TRACE
lang.java.OutOfMemoryError: (Could not allocate JNI Env)
at lang.java.Thread.nativeCreate(Native Method)
at lang.java.Thread.start(Thread.java:1063)
at concurrent.util.java.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:921)
at concurrent.util.java.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
at okhttp3.intercom.io.ConnectionPool.put(Native Method)
at okhttp3.intercom.io.OkHttpClient$1.put(Native Method)
at connection.internal.okhttp3.intercom.io.StreamAllocation.findConnection(Native Method)
at connection.internal.okhttp3.intercom.io.StreamAllocation.findHealthyConnection(Native Method)
at connection.internal.okhttp3.intercom.io.StreamAllocation.newStream(Native Method)
at connection.internal.okhttp3.intercom.io.ConnectInterceptor.intercept(Native Method)
at http.internal.okhttp3.intercom.io.RealInterceptorChain.proceed(Native Method)
at http.internal.okhttp3.intercom.io.RealInterceptorChain.proceed(Native Method)
at cache.internal.okhttp3.intercom.io.CacheInterceptor.intercept(Native Method)
at http.internal.okhttp3.intercom.io.RealInterceptorChain.proceed(Native Method)
at http.internal.okhttp3.intercom.io.RealInterceptorChain.proceed(Native Method)
at http.internal.okhttp3.intercom.io.BridgeInterceptor.intercept(Native Method)
at http.internal.okhttp3.intercom.io.RealInterceptorChain.proceed(Native Method)
at http.internal.okhttp3.intercom.io.RetryAndFollowUpInterceptor.intercept(Native Method)
at http.internal.okhttp3.intercom.io.RealInterceptorChain.proceed(Native Method)
at http.internal.okhttp3.intercom.io.RealInterceptorChain.proceed(Native Method)
at api.sdk.android.intercom.io.ShutdownInterceptor.intercept(Native Method)
at http.internal.okhttp3.intercom.io.RealInterceptorChain.proceed(Native Method)
at http.internal.okhttp3.intercom.io.RealInterceptorChain.proceed(Native Method)
at api.sdk.android.intercom.io.RetryInterceptor.intercept(Native Method)
at http.internal.okhttp3.intercom.io.RealInterceptorChain.proceed(Native Method)
at http.internal.okhttp3.intercom.io.RealInterceptorChain.proceed(Native Method)
at api.sdk.android.intercom.io.UserIdentityInterceptor.intercept(Native Method)
at http.internal.okhttp3.intercom.io.RealInterceptorChain.proceed(Native Method)
at http.internal.okhttp3.intercom.io.RealInterceptorChain.proceed(Native Method)
at okhttp3.intercom.io.RealCall.getResponseWithInterceptorChain(Native Method)
at okhttp3.intercom.io.RealCall$AsyncCall.execute(Native Method)
at internal.okhttp3.intercom.io.NamedRunnable.run(Native Method)
at concurrent.util.java.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at concurrent.util.java.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at lang.java.Thread.run(Thread.java:818)
```

**Comment by noinlijin** [comment] 2017-08-15 00:39
our app start use intercom is version of 18，after we use intercom，this crash appear，


![image](https://user-images.githubusercontent.com/3073370/29297689-421da4c4-8195-11e7-9dc9-2e7b62a2fdc3.png)

**Comment by noinlijin** [comment] 2017-08-15 00:42
and another crash from our app version of 20, the intercom version is 4.0.1

![image](https://user-images.githubusercontent.com/3073370/29297724-8b14f452-8195-11e7-9ad4-0ee4a1db0ee5.png)

![image](https://user-images.githubusercontent.com/3073370/29297755-b34f078c-8195-11e7-8693-d4e8b7022e11.png)

**Comment by noinlijin** [comment] 2017-08-15 01:00
time from 2017-8-9, the crash rate is increase more，because we update intercom version to 4.0.1, before version also have this crash, but The probability of occurrence is much lower 

![image](https://user-images.githubusercontent.com/3073370/29298075-ccf7115a-8197-11e7-91b6-adb67d6e7aa7.png)

**Comment by DaleCantwell** [comment] 2017-08-22 13:22
@noinlijin just to confirm, is Intercom causing 100% of the `OutOfMemoryError` type errors that your app is seeing?

As Skyler said above I think it's worth profiling the app and seeing if there is another cause of the OOM errors. I'll keep digging from our side.

**Comment by ronocod** [comment] 2017-09-08 12:49
This looks like an OutOfMemoryError caused by us trying to open a network connection while your app is out of memory. There's nothing we can do to protect against this, it's likely caused by high memory usage in your app. Closing this as it's not an issue with our SDK.

**Closed by ronocod** 2017-09-08 12:49 UTC
