### ISSUE TITLE
class io.intercom.android.sdk.gcm.GcmBroadcastReceiver does not exist

### ISSUE THREAD

**Issue by muazzam27** [intercom/intercom-android#271] opened 2016-10-15 20:59 UTC
class io.intercom.android.sdk.gcm.GcmBroadcastReceiver does not exist

**Comment by harkin** [comment] 2016-10-17 09:07
dupe of https://github.com/intercom/intercom-android/issues/270

**Closed by harkin** 2016-10-17 09:07 UTC
