### ISSUE TITLE
App Crashes 

### ISSUE THREAD

**Issue by NammariMarkavip** [intercom/intercom-android#178] opened 2016-02-10 10:19 UTC
<img width="1179" alt="screen shot 2016-02-10 at 12 17 54 pm" src="https://cloud.githubusercontent.com/assets/6898452/12944548/721aa9a4-cff0-11e5-904c-8e65d38b0fd1.png">

**Comment by NammariMarkavip** [comment] 2016-02-10 10:20
version io.intercom.android:intercom-sdk:1.1.12@aar

**Comment by harkin** [comment] 2016-02-10 10:21
closing as this is a duplicate of https://github.com/intercom/intercom-android/issues/176

we're looking into this one and hope to have a fix ready in our next release

**Closed by harkin** 2016-02-10 10:21 UTC

**Comment by NammariMarkavip** [comment] 2016-02-14 17:58
+1
