### ISSUE TITLE
Crash - Permission Denial: starting Intent { act=android.intent.action.VIEW ...

### ISSUE THREAD

**Issue by alexblack** [intercom/intercom-android#302] opened 2017-01-09 19:44 UTC
Crash: http://crashes.to/s/7a96d202228

## Version info
  - Intercom for Android version:3.0.14

```
Fatal Exception: java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.VIEW dat=https://support.google.com/... flg=0x10000000 cmp=com.alibaba.intl.android.apps.poseidon/com.alibaba.android.intl.weex.activity.WeexPageActivity } from ProcessRecord{e76b005 24240:com.aadhk.woinvoice/u0a140, isShadow:false} (pid=24240, uid=10140) not exported from uid 10204
       at android.os.Parcel.readException(Parcel.java:1599)
       at android.os.Parcel.readException(Parcel.java:1552)
       at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2826)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1518)
       at android.app.Activity.startActivityForResult(Activity.java:3969)
       at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:48)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:77)
       at android.app.Activity.startActivityForResult(Activity.java:3929)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
       at android.app.Activity.startActivity(Activity.java:4252)
       at android.app.Activity.startActivity(Activity.java:4220)
       at io.intercom.android.sdk.utilities.IntentUtils.safelyOpenIntent(IntentUtils.java:17)
       at io.intercom.android.sdk.utilities.LinkOpener.openUrl(LinkOpener.java:82)
       at io.intercom.android.sdk.utilities.LinkOpener.handleUrl(LinkOpener.java:27)
       at io.intercom.android.sdk.utilities.TrackingLinkMovementMethod.onTouchEvent(TrackingLinkMovementMethod.java:54)
       at android.widget.TextView.onTouchEvent(TextView.java:8934)
       at android.view.View.dispatchTouchEvent(View.java:9427)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
       at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2451)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1770)
       at android.app.Activity.dispatchTouchEvent(Activity.java:2817)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:67)
       at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2412)
       at android.view.View.dispatchPointerEvent(View.java:9658)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4828)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4686)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4191)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4244)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4210)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4356)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4218)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4413)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4191)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4244)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4210)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4218)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4191)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6645)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6619)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6562)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6840)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:328)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:5896)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

**Comment by ronocod** [comment] 2017-01-09 21:08
This is caused by a known bug with an Alibaba app: https://github.com/alibaba/weex/issues/2139

However we can do a better job of handling a `SecurityException` here, so we'll take a look into it.

**Comment by alexblack** [comment] 2017-01-09 21:10
Sounds good, yes catching exceptions like that instead of crashing the entire app would be preferable :)

**Comment by ronocod** [comment] 2017-01-23 11:36
Closing this as we catch SecurityExceptions here starting in 3.0.19.

**Closed by ronocod** 2017-01-23 11:36 UTC
