### ISSUE TITLE
AssertionError in AppConfig.java

### ISSUE THREAD

**Issue by renard314** [intercom/intercom-android#120] opened 2015-08-19 07:07 UTC
Only happens sporadically and on Samsung Lollipop devices.

Library Version: 1.1.2

java.lang.AssertionError
       at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:733)
       at com.google.gson.internal.bind.TypeAdapters$26.create(TypeAdapters.java:759)
       at com.google.gson.Gson.getAdapter(Gson.java:359)
       at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:55)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:99)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:219)
       at com.google.gson.internal.bind.ObjectTypeAdapter.write(ObjectTypeAdapter.java:107)
       at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
       at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:96)
       at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:60)
       at com.google.gson.Gson.toJson(Gson.java:600)
       at com.google.gson.Gson.toJson(Gson.java:579)
       at com.google.gson.Gson.toJson(Gson.java:534)
       at com.google.gson.Gson.toJson(Gson.java:514)
       at io.intercom.android.sdk.identity.AppConfig.update(AppConfig.java:91)
       at io.intercom.android.sdk.identity.AppIdentity.updateAppConfig(AppIdentity.java:61)
       at io.intercom.android.sdk.identity.IdentityStore.setAppConfig(IdentityStore.java:55)
       at io.intercom.android.sdk.api.CallbackHolder.updateAppConfig(CallbackHolder.java:113)
       at io.intercom.android.sdk.api.CallbackHolder.updateBaseResponseObjects(CallbackHolder.java:105)
       at io.intercom.android.sdk.api.CallbackHolder.access$000(CallbackHolder.java:28)
       at io.intercom.android.sdk.api.CallbackHolder$2.success(CallbackHolder.java:44)
       at io.intercom.android.sdk.api.CallbackHolder$2.success(CallbackHolder.java:41)
       at io.intercom.android.sdk.api.Api$1.success(Api.java:195)
       at io.intercom.android.sdk.api.Api$1.success(Api.java:191)
       at retrofit.CallbackRunnable$1.run(CallbackRunnable.java:45)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5832)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by DaleCantwell** [comment] 2015-08-20 10:16
@renard314 thanks for letting us know about this issue and providing us with your error log. We will look into this and let you know what we find.
To help us reproduce this error, was it a range of Samsung phones or was there one device in particular?

**Comment by renard314** [comment] 2015-08-20 10:30
Thanks for your quick reply. I've made the Fabric crashlog available http://crashes.to/s/1a6701b6e19.
It seems that it mostly happens on Samsung Galaxy S5.

**Comment by harkin** [comment] 2015-08-24 09:13
http://crashes.to/s/9ae1270571d second trace of it happening in the app config

**Comment by harkin** [comment] 2015-08-24 09:21
Both of these are places we're using Gson to map something from json. Samsung doesn't like that :( I read something recently about a particular phone having a version of Gson bundled with it that causes issues. I'll try to find that source again and see if it is the S5. In the meantime switching to v1.1.3 will help if it is a 'the wrong gson is being loaded' issue

**Comment by harkin** [comment] 2015-08-24 09:32
@renard314 do you have proguard enabled in your app?

**Comment by harkin** [comment] 2015-08-24 13:48
http://crashes.to/s/3b0d26bea3d

**Comment by gennadiiivanov** [comment] 2015-08-24 15:07
> @renard314 do you have proguard enabled in your app?

@harkin we don't have proguard enabled in the app but we have the same exception.

**Comment by renard314** [comment] 2015-08-26 03:03
I don't have proguard enabled.

**Comment by renard314** [comment] 2015-08-28 06:21
Another crash that looks related. This time in library 1.1.3
http://crashes.to/s/37c7c086b9b

**Comment by gennadiiivanov** [comment] 2015-09-02 14:55
@harkin what is the status of this issue? When do you plan to fix and release it?

**Comment by harkin** [comment] 2015-09-02 16:47
I'll be working on this tomorrow hopefully, no ETA for a fix but I'm hopeful that I'll find the cause of this before we finish our Marshmallow QA run so we can bundle the fix in with that update

**Comment by harkin** [comment] 2015-09-03 14:22
Two things I've found about this: 
* every other report on stackoverflow etc is related to proguard obfuscation
* lollipop on the S5 has a _really_ dodgy implementation of ART

**Comment by gennadiiivanov** [comment] 2015-09-03 14:31
@harkin we are not using proguard and we have the same crash. We are using multidex.

**Comment by harkin** [comment] 2015-09-03 14:35
I wonder if multidexing does some renaming/obfuscation of classes as part of how it operates. I'll look into this next. Are you also multidexing your app @renard314?

**Comment by renard314** [comment] 2015-09-03 14:42
No we are not using it. Have you considered catching that exception and sending the logs/raw json back to GA or some other reporting service for analysis?

**Comment by harkin** [comment] 2015-09-03 15:41
Very much considering catching the exception here and having a smart fallback. It's not a solution I like overly much but this _seems_ to be a very particular Samsung issue.

We have very limited options for reporting these things from the library. We don't want to include something like GA or Fabric or other analytics services in there because that would inflate the library size significantly (in terms of KB and method count).

**Comment by renard314** [comment] 2015-09-17 05:14
I understand. Would you please consider releasing a hot fix for this crash?  Even just swallowing the exception would be better than crashing and bringing down the client app. 
Its by far the most often occurring crash on crashlytics for us.

**Comment by DaleCantwell** [comment] 2015-09-17 09:28
@renard314 The next version that ships (targeting this week) will consume those GSON errors, I'll follow up on this to see if we can figure out  a better solution here. Let me know if you are ever able to reproduce this in house. We could gather a lot more information if we could reproduce the issue.

**Comment by harkin** [comment] 2015-09-21 12:37
this is fixed in the latest version

**Closed by harkin** 2015-09-21 12:37 UTC
