### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Jonfor** [intercom/intercom-android#177] opened 2016-02-03 21:34 UTC
I'm getting a memory leak in one of my fragments. I am running Android 6.0.1 on a Nexus 5X. Here is the output of LeakCanary:

![screenshot_20160203-162850](https://cloud.githubusercontent.com/assets/3246528/12797815/ee0998fc-ca93-11e5-8d2f-f5a28686913c.png)

**Comment by harkin** [comment] 2016-02-08 12:07
Hi @Jonfor thanks for letting us know about this. I'm investigating this now. Do you have any additional details about how often this happens or any steps to reproduce?

I've never had leak canary report leaks around how we display handle references to an Activity like this. If I'm reading it correctly it looks like the activity itself isn't being leaked but a textview you were displaying?  Are you specifying `RefWatcher`s yourself or is this default leak canary behaviour? If it's custom could you explain when you'd expect it to be GCed?

The SDK should be releasing the reference to your activity when the onPause lifecycle is hit for that activity.

**Comment by Jonfor** [comment] 2016-02-08 15:07
Well I think this may be my fault actually! I specified the `RefWatcher` myself to watch a `TextView` with an anonymous `OnClickListener` that I create in my fragment's `onCreateView` method. It happens every time I open the fragment with that `TextView`.

**Comment by harkin** [comment] 2016-02-08 16:50
That's good news (for me anyway). I'd love to close this out if it's a non-issue or find what part of the SDK is causing this for you if you think Intercom is related.

As I understand LeakCanary the fact that it mentions the SDK might be coincidental if there's a second chain keeping a reference alive. One way to check would be to remove Intercom and see if you still see the leak.

If you think the SDK is unrelated I'll close this out.

**Comment by Jonfor** [comment] 2016-02-08 21:37
Yup, It was all me!

**Comment by harkin** [comment] 2016-02-09 09:43
Glad you found the problem :+1: Let us know if you have any issues with the library!

**Closed by harkin** 2016-02-09 09:43 UTC
