### ISSUE TITLE
Intercom is showing an error: E/Intercom-Android: ERROR: Api call failed: Canceled

### ISSUE THREAD

**Issue by EstebanSelaya** [intercom/intercom-android#145] opened 2015-11-03 18:24 UTC
After making the following call using the Intercom-java framework:

Intercom.client().displayConversationsList();

A new activity opens up and shows an error message where normally a conversation list would be. "Unable to load conversations". Further, the logs show the following error: "E/Intercom-Android: ERROR: Api call failed: Canceled".

I'm unable to find any documentation to this specific error. Any help would be appreciated.

**Comment by harkin** [comment] 2015-11-04 13:11
I haven't come across that error in the library before. For calls to our server we surface any problems that the networking stack (okhttp) tells us about. We aren't explicitly cancelling a request there. The other reason that an exception with that reason gets thrown is if the response is `null` which it also shouldn't be.

I've got a few questions that'll hopefully narrow down why this is happening for you. Did this break suddenly for you or has it never worked? What version of the library are you using? Are you going through any proxy on the device? Also could you give some general details about the device you're using; what phone it is, if it's rooted, what version of android?

**Comment by EstebanSelaya** [comment] 2015-11-04 16:14
1. This suddenly broke down for us.

2. We're using the following import:

compile ('io.intercom.android:intercom-sdk:1.+@aar') {
        transitive = true
    }


3. We aren't going through any kind of proxy on the device. We're using our
office WiFi for network connection.

4. Test Device:

Moto X Pure Edition, Android version 5.1.1, unrooted.

On Wed, Nov 4, 2015 at 5:11 AM, Henry <notifications@github.com> wrote:

> I haven't come across that error in the library before. For calls to our
> server we surface any problems that the networking stack (okhttp) tells us
> about. We aren't explicitly cancelling a request there. The other reason
> that an exception with that reason gets thrown is if the response is null
> which it also shouldn't be.
>
> I've got a few questions that'll hopefully narrow down why this is
> happening for you. Did this break suddenly for you or has it never worked?
> What version of the library are you using? Are you going through any proxy
> on the device? Also could you give some general details about the device
> you're using; what phone it is, if it's rooted, what version of android?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/intercom/intercom-android/issues/145#issuecomment-153715747>
> .
>



-- 
*Esteban Selaya*
Android Engineer | Hart

esteban.selaya@hart.com | hart.com
20101 SW Birch St. #260 Newport Beach, CA. 92660

**Comment by harkin** [comment] 2015-11-04 18:16
Hm, we released a new version of the library at around 5pm GMT yesterday, roughly two hours before you opened the initial issue. Had you noticed it before that? The new version didn't have any changes that would affect that part of the codebase so it should be unrelated, but the timing is a little too coincidental to ignore.

**Comment by EstebanSelaya** [comment] 2015-11-04 18:58
No I hadn't noticed anything before yesterday. To be fair though, I haven't
really looked at it since I set it up initially.

I don't think we've made any changes that would affect Intercom, but I'll
go over our Intercom user registration process and make sure it follows the
tutorial for both identified and unidentified users.

On Wed, Nov 4, 2015 at 10:16 AM, Henry <notifications@github.com> wrote:

> Hm, we released a new version of the library at around 5pm GMT yesterday,
> roughly two hours before you opened the initial issue. Had you noticed it
> before that? The new version didn't have any changes that would affect that
> part of the codebase so it should be unrelated, but the timing is a little
> too coincidental to ignore.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/intercom/intercom-android/issues/145#issuecomment-153815962>
> .
>



-- 
*Esteban Selaya*
Android Engineer | Hart

esteban.selaya@hart.com | hart.com
20101 SW Birch St. #260 Newport Beach, CA. 92660

**Comment by EstebanSelaya** [comment] 2015-11-05 16:42
Ok. After much tweaking to completely remove "unidentified" users. I've set
up a Intercom following the tutorial strictly for "identified" users only.
We're registering new users with the attributes "name" and "email".

The following error message now occurs when attempting the following:

 Intercom.client().displayConversationsList();

Error Message:

E/Intercom-Android: ERROR: Failed to register or update user: Canceled
E/Intercom-Android: ERROR: Api call failed: Canceled

Seems like the same error as before. Except now even user registration is
failing.

On Wed, Nov 4, 2015 at 10:58 AM, Esteban Selaya <esteban.selaya@hart.com>
wrote:

> No I hadn't noticed anything before yesterday. To be fair though, I
> haven't really looked at it since I set it up initially.
>
> I don't think we've made any changes that would affect Intercom, but I'll
> go over our Intercom user registration process and make sure it follows the
> tutorial for both identified and unidentified users.
>
> On Wed, Nov 4, 2015 at 10:16 AM, Henry <notifications@github.com> wrote:
>
>> Hm, we released a new version of the library at around 5pm GMT yesterday,
>> roughly two hours before you opened the initial issue. Had you noticed it
>> before that? The new version didn't have any changes that would affect that
>> part of the codebase so it should be unrelated, but the timing is a little
>> too coincidental to ignore.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/intercom/intercom-android/issues/145#issuecomment-153815962>
>> .
>>
>
>
>
> --
> *Esteban Selaya*
> Android Engineer | Hart
>
> esteban.selaya@hart.com | hart.com
> 20101 SW Birch St. #260 Newport Beach, CA. 92660
>
>


-- 
*Esteban Selaya*
Android Engineer | Hart

esteban.selaya@hart.com | hart.com
20101 SW Birch St. #260 Newport Beach, CA. 92660

**Comment by EstebanSelaya** [comment] 2015-11-05 16:43
*Edit We're also making the call to register an identified user just before
the displayConversationsList() call:

Map<String, Object> userMap = new HashMap<>();
userMap.put("name", name);
userMap.put("email", email);
Intercom.client().registerIdentifiedUser(new
Registration().withUserAttributes(userMap));

On Thu, Nov 5, 2015 at 8:42 AM, Esteban Selaya <esteban.selaya@hart.com>
wrote:

> Ok. After much tweaking to completely remove "unidentified" users. I've
> set up a Intercom following the tutorial strictly for "identified" users
> only. We're registering new users with the attributes "name" and "email".
>
> The following error message now occurs when attempting the following:
>
>  Intercom.client().displayConversationsList();
>
> Error Message:
>
> E/Intercom-Android: ERROR: Failed to register or update user: Canceled
> E/Intercom-Android: ERROR: Api call failed: Canceled
>
> Seems like the same error as before. Except now even user registration is
> failing.
>
> On Wed, Nov 4, 2015 at 10:58 AM, Esteban Selaya <esteban.selaya@hart.com>
> wrote:
>
>> No I hadn't noticed anything before yesterday. To be fair though, I
>> haven't really looked at it since I set it up initially.
>>
>> I don't think we've made any changes that would affect Intercom, but I'll
>> go over our Intercom user registration process and make sure it follows the
>> tutorial for both identified and unidentified users.
>>
>> On Wed, Nov 4, 2015 at 10:16 AM, Henry <notifications@github.com> wrote:
>>
>>> Hm, we released a new version of the library at around 5pm GMT
>>> yesterday, roughly two hours before you opened the initial issue. Had you
>>> noticed it before that? The new version didn't have any changes that would
>>> affect that part of the codebase so it should be unrelated, but the timing
>>> is a little too coincidental to ignore.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/intercom/intercom-android/issues/145#issuecomment-153815962>
>>> .
>>>
>>
>>
>>
>> --
>> *Esteban Selaya*
>> Android Engineer | Hart
>>
>> esteban.selaya@hart.com | hart.com
>> 20101 SW Birch St. #260 Newport Beach, CA. 92660
>>
>>
>
>
> --
> *Esteban Selaya*
> Android Engineer | Hart
>
> esteban.selaya@hart.com | hart.com
> 20101 SW Birch St. #260 Newport Beach, CA. 92660
>
>


-- 
*Esteban Selaya*
Android Engineer | Hart

esteban.selaya@hart.com | hart.com
20101 SW Birch St. #260 Newport Beach, CA. 92660

**Comment by harkin** [comment] 2015-11-12 13:12
@EstebanSelaya sorry for the delay in getting back to you on this. Could you check to make sure you're using the correct api-key? In current versions using an incorrect api key will cause the error message you're seeing now, I'm going to work on making that more informative

**Comment by vishna** [comment] 2015-11-17 17:00
Also getting this issue, plus network call isn't even fired.

**Comment by harkin** [comment] 2015-11-18 11:54
copying in from https://github.com/intercom/intercom-android/issues/153

So API_KEY and APP_ID is all set as requested in your "Add Integration" manual. Registering anything fails, pretty much boils down to some RetrofitError - the API request for some reason is never actually fired.

Using `intercom-sdk-base:1.+@aar` so no GCM. Sidenote, using + notation for the version, as you recommend, is not a good practice.

```java
io.intercom.retrofit.RetrofitError: Canceled


error = {io.intercom.retrofit.RetrofitError@4530} "io.intercom.retrofit.RetrofitError: Canceled"
 converter = null
 kind = {io.intercom.retrofit.RetrofitError$Kind@4747} "NETWORK"
 response = null
 successType = null
 url = {java.lang.String@4748} "https://mobileapi-v2.intercom.io/oreo/users"
 cause = {java.io.IOException@4749} "java.io.IOException: Canceled"
 detailMessage = {java.lang.String@4750} "Canceled"
 stackState = null
 stackTrace = {java.lang.StackTraceElement[11]@4772} 
 suppressedExceptions = {java.util.Collections$EmptyList@4753}  size = 0
 shadow$_klass_ = {java.lang.Class@4008} "class io.intercom.retrofit.RetrofitError"
 shadow$_monitor_ = -1781342583

0 = {java.lang.StackTraceElement@4775} "io.intercom.retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:395)"
1 = {java.lang.StackTraceElement@4776} "io.intercom.retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)"
2 = {java.lang.StackTraceElement@4777} "io.intercom.retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)"
3 = {java.lang.StackTraceElement@4778} "io.intercom.retrofit.CallbackRunnable.run(CallbackRunnable.java:42)"
4 = {java.lang.StackTraceElement@4779} "java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)"
5 = {java.lang.StackTraceElement@4780} "java.util.concurrent.FutureTask.run(FutureTask.java:237)"
6 = {java.lang.StackTraceElement@4781} "java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)"
7 = {java.lang.StackTraceElement@4782} "java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)"
8 = {java.lang.StackTraceElement@4783} "java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)"
9 = {java.lang.StackTraceElement@4784} "java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)"
10 = {java.lang.StackTraceElement@4785} "java.lang.Thread.run(Thread.java:818)"
```

**Comment by harkin** [comment] 2015-11-18 13:50
@vishna have you registered a user with Intercom (called `Intercom.client().register(un)identifiedUser()`) when you see this with in the logs? 

I'm becoming more confident that this is just a logging issue. Whenever we communicate with our servers we check that a user has been registered and that app details have been provided. If either of those are false we'll drop that request. This results in the log you're seeing. 

If you don't have a user registered there are situations where the library will still try to communicate with our server (for example to increment session count). This request gets dropped because there actually isn't a user registered (this is the correct behaviour) and a log message gets generated. That log message is completely spurious and can be ignored.

After you have a user registered (and haven't called `reset()`) you won't see that message about cancelled requests anymore. If you do then this isn't just a logging issue, but I haven't been able to reproduce a scenario where a request that should be sent isn't being sent. 

I'm currently looking at reducing the number of requests we initiate that we know we'll be dropping later on, I'll change how the logs work here so there aren't any misleading ones generated and I'll see if I can't make them a bit more descriptive in this case too.

**Comment by vishna** [comment] 2015-11-18 16:44
@harkin in short answer yes.

So we need minimal integration on our side, just notify intercom whenever user is logged in or is logged out/opens the app. Nothing more.

I've created this wrapper so I can plug in/out Intercom support more easily. It listens to Activity changes and then fires appropriate calls based on the account object being present or not (if it's not there user is logged out obviously).

Flags are there to specifically prevent calling register/unregister twice. The thing is the very first time, this call gets triggered (after fresh install), the actual HTTP request is never fired (checked with Charles Proxy).

```java
import android.app.Activity;
import android.app.Application;
import android.content.res.Resources;
import android.os.Bundle;

import com.baseapp.eyeem.R;
import com.eyeem.mjolnir.Account;

import io.intercom.android.sdk.Intercom;
import io.intercom.android.sdk.identity.Registration;

/**
 * Intercom integration.
 *
 * Created by vishna on 17/11/15.
 */
public class EyeCom {

   private static EyeCom sClient;

   Intercom client;
   boolean isLoggedIn;
   boolean isRegistered;

   /**
    * Call from App on create
    */
   public static void init(Application app) {
      Resources r = app.getResources();
      Intercom.initialize(
         app,
         r.getString(R.string.intercom_api_key),
         r.getString(R.string.intercom_app_id));
      app.registerActivityLifecycleCallbacks(new ActivityLifecycle());
   }

   private EyeCom() {
      if (client == null) {
         client = Intercom.client();
      }
   }

   public static EyeCom client() {
      if (sClient == null) {
         sClient = new EyeCom();
      }
      return sClient;
   }

   public synchronized void register(Account account) {
      if (account == null && isLoggedIn) {
         client.reset();
         isLoggedIn = false;
         isRegistered = false;
      }

      if (account != null && isRegistered && !isLoggedIn) {
         isRegistered = false;
      }

      if (!isRegistered) {
         if (account != null) {
            client.registerIdentifiedUser(new Registration().withUserId(account.id));
            isLoggedIn = true;
         }
         else {
            client.registerUnidentifiedUser();
            isLoggedIn = false;
         }

         isRegistered = true;
      }
   }

   private final static class ActivityLifecycle implements Application.ActivityLifecycleCallbacks {
      @Override public void onActivityCreated(Activity activity, Bundle savedInstanceState) {
         EyeCom.client().register((Account)activity.getSystemService("defaultAccount"));
      }

      //region no-op
      @Override public void onActivityStarted(Activity activity) {}
      @Override public void onActivityResumed(Activity activity) {}
      @Override public void onActivityPaused(Activity activity) {}
      @Override public void onActivityStopped(Activity activity) {}
      @Override public void onActivitySaveInstanceState(Activity activity, Bundle outState) {}
      @Override public void onActivityDestroyed(Activity activity) {}
      //endregion
   }

}
```

**Comment by harkin** [comment] 2015-11-27 16:52
I've just pushed a release that does two things: improves logging here and also removes some cases where things were incorrectly being logged.

@vishna @EstebanSelaya if you guys could check out 1.1.10 and see if you're still seeing an issue I'd love to know and we can go from there

**Comment by vishna** [comment] 2015-12-01 11:23
@harkin cool, seems to be working now, thanks!

**Comment by vishna** [comment] 2015-12-01 11:28
@harkin btw I see you're using okhttp, just like us - any chance you release version of this library without okhttp classes repackaged so we could reduce total count of methods?

**Comment by harkin** [comment] 2015-12-01 16:28
@vishna Glad to hear it's working now :) I'll close this out, let me know if you see any issues

For the current version (1.x.x) it's unlikely we'll offer anything without repackaged dependencies. I've written about why this is a good thing for us as a library to do [here](https://github.com/intercom/intercom-android/issues/126#issuecomment-135748670) (there are some linked issues there that might have more interesting comments). The TL;DR is that we feel it's a nuanced issue with many pros and cons and right now the positives we get from doing this outweigh the negatives. 

We are definitely taking this feedback on board though and looking at other options that might bring more positives without making everything more complex and introducing scope for bugs. Any change is ~probably~ going to break backwards compatibility which is why it's unlikely at the moment.

**Comment by mawadi7** [comment] 2016-03-01 16:31
@harkin thank you for explain. However, this works perfect on 1.1.10 but same error on next versions! 
E/Intercom-Android: ERROR: Failed to register or update user: unknown error . not sure where the problem is but it works on 1.1.10 we missing a lot of very good features in new versions ! what to do?

**Comment by hanspeide** [comment] 2016-03-27 09:19
I'm getting the following when calling `Intercom.client().reset()`:
`E/Intercom-Android: ERROR: Api call failed: application interceptor io.intercom.android.sdk.api.IdentityInterceptor@a220820 returned null`

Registration works just fine, and I can see the messages that has been sent back and forth. Any chance you could make it possible to set a flag that enables more logging? Messages like the one above are not really helpful when trying to identify the issue.

**Comment by ronocod** [comment] 2016-08-31 09:38
Sorry for the delay in getting back to this @mawadi7, the code here has changed significantly in version 3.0. Can you check if your issue is fixed in the newest release?

**Closed** 2016-09-07 09:31 UTC
