### ISSUE TITLE
ConcurrentModificationException in NexusClient

### ISSUE THREAD

**Issue by renard314** [intercom/intercom-android#133] opened 2015-09-16 08:59 UTC
http://crashes.to/s/ae51e3f7b58

Library Version: 1.1.3

**Comment by DaleCantwell** [comment] 2015-09-16 11:00
@renard314 thank you for reporting that issue, we have encountered that issue ourselves and are looking into solutions. I'll post any updated to this thread. 
It should be very infrequent but let me know if you are seeing this often.

**Comment by renard314** [comment] 2015-09-16 11:03
Thank you for the heads up. Its indeed happening very rarely.

**Comment by harkin** [comment] 2015-09-21 12:41
this looks to be a dupe of https://github.com/intercom/intercom-android/issues/119. I'm going to be looking into why this is happening soon

**Closed by harkin** 2015-09-21 12:41 UTC
