### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: cache is closed (DiskLruCache.java line 618)

### ISSUE THREAD

**Issue by razmaimon** [intercom/intercom-android#409] opened 2017-08-28 04:09 UTC
## Version info
  - Intercom for Android version: 3.1.3 (new version has the latest)
  - Android OS version: 7.0
  - Android Device: Samsung SM-G390Y
4.92 GiB disk free space
397.00 MiB FREE RAM

Fatal Exception: java.lang.IllegalStateException: cache is closed
       at io.intercom.com.bumptech.glide.disklrucache.DiskLruCache.checkNotClosed(DiskLruCache.java:618)
       at io.intercom.com.bumptech.glide.disklrucache.DiskLruCache.get(DiskLruCache.java:407)
       at io.intercom.android.sdk.imageloader.LongTermImageDiskCache.get(LongTermImageDiskCache.java:73)
       at io.intercom.android.sdk.imageloader.LongTermImageLoader.loadImage(LongTermImageLoader.java:57)
       at io.intercom.android.sdk.conversation.ReactionInputView.setUpReactions(ReactionInputView.java:113)
       at io.intercom.android.sdk.conversation.ConversationFragment.configureInputView(ConversationFragment.java:394)
       at io.intercom.android.sdk.conversation.ConversationFragment.onViewCreated(ConversationFragment.java:360)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1314)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
       at android.support.v4.app.BackStackRecord.executePopOps(BackStackRecord.java:807)
       at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2360)
       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
       at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
       at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:823)
       at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:776)
       at android.support.v4.app.FragmentActivity.onBackPressed(FragmentActivity.java:178)
       at io.intercom.android.sdk.activities.IntercomMessengerActivity.applyBackOrCloseMessenger(IntercomMessengerActivity.java:175)
       at io.intercom.android.sdk.activities.IntercomMessengerActivity.onBackPressed(IntercomMessengerActivity.java:165)
       at android.app.Activity.onKeyUp(Activity.java:2875)
       at android.view.KeyEvent.dispatch(KeyEvent.java:3361)
       at android.app.Activity.dispatchKeyEvent(Activity.java:3176)
       at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:541)
       at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
       at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:319)
       at com.appsee.z.dispatchKeyEvent(q:1013)
       at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:447)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4999)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4961)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4490)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4543)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4509)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4642)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4517)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4699)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4490)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4543)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4509)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4517)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4490)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4543)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4509)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4675)
       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4844)
       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3042)
       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2578)
       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2569)
       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3019)
       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:323)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:6836)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by ronocod** [comment] 2017-08-28 09:27
Duplicate of https://github.com/intercom/intercom-android/issues/310

**Closed** 2017-08-28 09:27 UTC
