### ISSUE TITLE
IAM shown after a conversation has been read

### ISSUE THREAD

**Issue by hanspeide** [intercom/intercom-android#243] opened 2016-08-18 14:39 UTC
## Version info
- Intercom for Android version: 3.0.3
- Android OS version: 6.0.0
- Android Device: Nexus 5X (Genymotion)
## Expected behavior

I have several fragments in a pager. For one of the fragments I would only like to show the unread counter when there's an incoming message (so I call setInAppMessageVisibility(Intercom.Visibility.GONE)), but for the other I want to show the IAM popup (and therefore call setInAppMessageVisibility(Intercom.Visibility.GONE).

I'm in the fragment that shows the counter. I receive a message, and open it. After this I go back to the fragment, and I can see that the unread counter is no longer visible, as expected. When I swipe to the other fragments the IAM should not be shown, as I've already opened and read it.
## Actual behavior

When I swipe to other fragments the IAM is shown, even though I've opened and read the conversation.

**Comment by ronocod** [comment] 2016-08-18 14:42
Video of bug in action: https://www.youtube.com/watch?v=3a6JzMff24c (thanks for this 😄 )

**Comment by hanspeide** [comment] 2016-09-19 21:08
Any updates on this issue?

**Comment by ronocod** [comment] 2016-09-21 09:33
We're working on a fix for this now, I'll post any updates we have here.

**Comment by ronocod** [comment] 2017-01-23 11:38
@hanspeide we've reworked this code a lot and we can't reproduce it as of 3.0.19. Can you try this version to see if it fixed your issue?

**Comment by ronocod** [comment] 2017-02-08 15:06
Closing this as it appears to be fixed.

**Closed by ronocod** 2017-02-08 15:06 UTC
