### ISSUE TITLE
java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by lithid** [intercom/intercom-android#176] opened 2016-02-02 16:07 UTC
We tried updating to the latest intercom sdk and still seeing the following error on devices randomly. These are happening to remote users and not devices in our device farm.

[report (2).txt](https://github.com/intercom/intercom-android/files/114236/report.2.txt)

**Comment by DaleCantwell** [comment] 2016-02-02 16:10
@lithid do you have any data on the devices it is happening to? Even just a couple of the devices to help us try reproduce it easier.

**Comment by lithid** [comment] 2016-02-02 16:12
![screen shot 2016-02-02 at 11 12 14 am](https://cloud.githubusercontent.com/assets/530067/12755547/e02d95fe-c99d-11e5-8f29-52f60f615fa4.png)

**Comment by lithid** [comment] 2016-02-02 16:13
Looks like it might be related to another issue we opened. https://github.com/intercom/intercom-android/issues/149

**Comment by DaleCantwell** [comment] 2016-02-02 16:17
It does look like the same thing alright, thanks for linking those up for us. We'll look into it now and update you ASAP.

**Comment by lithid** [comment] 2016-02-04 14:41
Good Morning. Are there any updates about this crash?

**Comment by harkin** [comment] 2016-02-08 12:14
I can't reproduce this issue locally on Samsung devices, but the ones I have access to are different versions. In particular, they're all GSM whereas the phones in that screenshot above are all CDMA. I'm not sure if/why that would make a difference.

I'm sure that it's not a data issue, i.e. that the adapter is always being notified of data updates. I'm investigating if we can do some bounds checking that will fix this (and not just push the error to somewhere down the line)

**Comment by NammariMarkavip** [comment] 2016-02-14 17:59
+1

**Comment by harkin** [comment] 2016-02-15 10:14
This is fixed in 1.1.15 :)

**Closed by harkin** 2016-02-15 10:14 UTC
Labels: bug
