### ISSUE TITLE
libpng warning: iCCP: Not recognizing known sRGB profile that has been edited

### ISSUE THREAD

**Issue by danikula** [intercom/intercom-android#67] opened 2015-04-29 14:18 UTC
Gradle complains during assembling build:

```
AAPT: /app/build/intermediates/exploded-aar/io.intercom.android/intercom-sdk/0.9.5/res/drawable-xxhdpi-v4/intercomsdk_sad_normal.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /app/build/intermediates/exploded-aar/io.intercom.android/intercom-sdk/0.9.5/res/drawable-xxhdpi-v4/intercomsdk_icn_pressed_close_icon_with_circle.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /app/build/intermediates/exploded-aar/io.intercom.android/intercom-sdk/0.9.5/res/drawable-xxhdpi-v4/intercomsdk_avatar.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /app/build/intermediates/exploded-aar/io.intercom.android/intercom-sdk/0.9.5/res/drawable-xxhdpi-v4/intercomsdk_icn_close_icon_with_circle.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /app/build/intermediates/exploded-aar/io.intercom.android/intercom-sdk/0.9.5/res/drawable-xxhdpi-v4/intercomsdk_happy_normal.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /app/build/intermediates/exploded-aar/io.intercom.android/intercom-sdk/0.9.5/res/drawable-xxhdpi-v4/intercomsdk_neutral_normal.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /app/build/intermediates/exploded-aar/io.intercom.android/intercom-sdk/0.9.5/res/drawable-xxhdpi-v4/intercomsdk_thumbs_up_normal.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /app/build/intermediates/exploded-aar/io.intercom.android/intercom-sdk/0.9.5/res/drawable-xxhdpi-v4/intercomsdk_thumbs_down_normal.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
```

Can you remove metadata from png resources as [Jake Wharton suggests](https://groups.google.com/d/msg/adt-dev/rjTQ_STR3OE/-UcNQRISTKsJ)?

**Comment by Harkin** [comment] 2015-04-29 14:42
yes, we certainly can :+1:

**Comment by DaleCantwell** [comment] 2015-04-29 18:22
Fixed in v0.9.6

**Comment by danikula** [comment] 2015-04-29 18:23
:+1:

**Closed by DaleCantwell** 2015-04-29 18:22 UTC

**Comment by linghp** [comment] 2015-09-22 03:38
how to resolved

**Comment by DaleCantwell** [comment] 2015-09-22 09:48
@linghp are you seeing this issue in our logs? If so what SDK version are you running?

**Comment by englenshan** [comment] 2017-03-29 08:05
how to resolved

**Comment by ronocod** [comment] 2017-03-29 10:36
@englenshan you can find information about this error and how to resolve it here: http://stackoverflow.com/questions/31495147/android-studio-libpng-warning-iccp-not-recognizing-known-srgb-profile-that-h

It's not an issue with our image files any more so it must be caused by your app's image files

**Comment by englenshan** [comment] 2017-03-30 03:39
thanks !
