### ISSUE TITLE
E/Intercom-Android: ERROR: Failed to register or update user: Canceled

### ISSUE THREAD

**Issue by vishna** [intercom/intercom-android#153] opened 2015-11-17 17:25 UTC
So API_KEY and APP_ID is all set as requested in your "Add Integration" manual. Registering anything fails, pretty much boils down to some RetrofitError - the API request for some reason is never actually fired.

Using `intercom-sdk-base:1.+@aar` so no GCM. Sidenote, using + notation for the version, as you recommend, is not a good practice.

```java
io.intercom.retrofit.RetrofitError: Canceled


error = {io.intercom.retrofit.RetrofitError@4530} "io.intercom.retrofit.RetrofitError: Canceled"
 converter = null
 kind = {io.intercom.retrofit.RetrofitError$Kind@4747} "NETWORK"
 response = null
 successType = null
 url = {java.lang.String@4748} "https://mobileapi-v2.intercom.io/oreo/users"
 cause = {java.io.IOException@4749} "java.io.IOException: Canceled"
 detailMessage = {java.lang.String@4750} "Canceled"
 stackState = null
 stackTrace = {java.lang.StackTraceElement[11]@4772} 
 suppressedExceptions = {java.util.Collections$EmptyList@4753}  size = 0
 shadow$_klass_ = {java.lang.Class@4008} "class io.intercom.retrofit.RetrofitError"
 shadow$_monitor_ = -1781342583

0 = {java.lang.StackTraceElement@4775} "io.intercom.retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:395)"
1 = {java.lang.StackTraceElement@4776} "io.intercom.retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)"
2 = {java.lang.StackTraceElement@4777} "io.intercom.retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)"
3 = {java.lang.StackTraceElement@4778} "io.intercom.retrofit.CallbackRunnable.run(CallbackRunnable.java:42)"
4 = {java.lang.StackTraceElement@4779} "java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)"
5 = {java.lang.StackTraceElement@4780} "java.util.concurrent.FutureTask.run(FutureTask.java:237)"
6 = {java.lang.StackTraceElement@4781} "java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)"
7 = {java.lang.StackTraceElement@4782} "java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)"
8 = {java.lang.StackTraceElement@4783} "java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)"
9 = {java.lang.StackTraceElement@4784} "java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)"
10 = {java.lang.StackTraceElement@4785} "java.lang.Thread.run(Thread.java:818)"
```

**Comment by harkin** [comment] 2015-11-18 11:53
closing as dupe of https://github.com/intercom/intercom-android/issues/145

re the sidenote, if you want you can specify the version, `1.1.9`

**Closed by harkin** 2015-11-18 11:53 UTC
