### ISSUE TITLE
NullPointerException on Writing to Segment.next

### ISSUE THREAD

**Issue by jackcsk** [intercom/intercom-android#314] opened 2017-03-02 07:11 UTC
## Version info
  - Intercom for Android version: 3.0.20
  - Android OS version: 7.0
  - Android Device: Samsung Galaxy S7

## Expected behavior
Operation completes successful

## Actual behavior
Crashed with NullPointerException

## Steps to reproduce
Not sure, as this issue is reported by Fabric Crashlytics

## Logs
```
Fatal Exception: java.lang.NullPointerException: Attempt to write to field 'io.intercom.okio.Segment io.intercom.okio.Segment.next' on a null object reference
       at io.intercom.okio.Segment.pop(Segment.java:85)
       at io.intercom.okio.Buffer.skip(Buffer.java:820)
       at io.intercom.okio.RealBufferedSource.skip(RealBufferedSource.java:308)
       at io.intercom.okhttp3.internal.ws.WebSocketReader$FramedMessageSource.close(WebSocketReader.java:309)
       at io.intercom.okio.RealBufferedSource.close(RealBufferedSource.java:434)
       at io.intercom.okhttp3.internal.Util.closeQuietly(Util.java:88)
       at io.intercom.okhttp3.ResponseBody.bytes(ResponseBody.java:130)
       at io.intercom.okhttp3.ResponseBody.string(ResponseBody.java:154)
       at io.intercom.android.sdk.nexus.NexusSocket.onMessage(NexusSocket.java:191)
       at io.intercom.okhttp3.internal.ws.RealWebSocket$1.onMessage(RealWebSocket.java:62)
       at io.intercom.okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:242)
       at io.intercom.okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:108)
       at io.intercom.okhttp3.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97)
       at io.intercom.okhttp3.ws.WebSocketCall.createWebSocket(WebSocketCall.java:152)
       at io.intercom.okhttp3.ws.WebSocketCall.access$000(WebSocketCall.java:41)
       at io.intercom.okhttp3.ws.WebSocketCall$1.onResponse(WebSocketCall.java:97)
       at io.intercom.okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)
       at io.intercom.okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
```

**Comment by ronocod** [comment] 2017-03-02 10:39
We're investigating this now, I'll keep you updated on any progress.

**Comment by ronocod** [comment] 2017-03-20 15:42
Can you try 3.1.1 to see if this is still happening? We're now using an updated WebSockets library.

**Comment by jackcsk** [comment] 2017-03-21 01:47
Thanks. I will include the updated version on our next release.
Given that it takes time to check if the issue occurs on new version, perhaps we can reopen the issue later if necessary?

**Comment by ronocod** [comment] 2017-03-21 09:08
Yes, I think that makes sense. I'll close this along with your other issue, if they occur again we can reopen.

**Comment by ronocod** [comment] 2017-04-04 09:39
Re-opening as https://github.com/intercom/intercom-android/issues/329 is a second report of this.

**Comment by henrikra** [comment] 2017-04-28 07:44
We got very similar crash on 3.1.3 :( Is there fix for this?

```
java.lang.NullPointerException Attempt to write to field 'io.intercom.okio.Segment io.intercom.okio.Segment.prev' on a null object reference 
    Segment.java:86 io.intercom.okio.Segment.pop
    Okio.java:85 io.intercom.okio.Okio$1.write
    AsyncTimeout.java:179 io.intercom.okio.AsyncTimeout$1.write
    RealBufferedSink.java:178 io.intercom.okio.RealBufferedSink.emit
    WebSocketWriter.java:152 io.intercom.okhttp3.internal.ws.WebSocketWriter.writeControlFrameSynchronized
    WebSocketWriter.java:111 io.intercom.okhttp3.internal.ws.WebSocketWriter.writeClose
    RealWebSocket.java:185 io.intercom.okhttp3.internal.ws.RealWebSocket.peerClose
    RealWebSocket.java:38 io.intercom.okhttp3.internal.ws.RealWebSocket.access$200
    RealWebSocket.java:84 io.intercom.okhttp3.internal.ws.RealWebSocket$1$2.execute
    NamedRunnable.java:32 io.intercom.okhttp3.internal.NamedRunnable.run
    ThreadPoolExecutor.java:1133 java.util.concurrent.ThreadPoolExecutor.runWorker
    ThreadPoolExecutor.java:607 java.util.concurrent.ThreadPoolExecutor$Worker.run
    Thread.java:761 java.lang.Thread.run
```

**Comment by henrikra** [comment] 2017-05-14 17:52
@ronocod @jackcsk  Again new one
Device info:
![image](https://cloud.githubusercontent.com/assets/12229968/26036480/204316fa-38e7-11e7-92b2-11d38160af98.png)

```
java.lang.NullPointerException Attempt to write to field 'io.intercom.okio.Segment io.intercom.okio.Segment.next' on a null object reference 
    Segment.java:85 io.intercom.okio.Segment.pop
    Buffer.java:1241 io.intercom.okio.Buffer.write
    Buffer.java:577 io.intercom.okio.Buffer.readFully
    RealBufferedSource.java:155 io.intercom.okio.RealBufferedSource.readFully
    WebSocketReader.java:171 io.intercom.okhttp3.internal.ws.WebSocketReader.readControlFrame
    WebSocketReader.java:106 io.intercom.okhttp3.internal.ws.WebSocketReader.processNextFrame
    RealWebSocket.java:97 io.intercom.okhttp3.internal.ws.RealWebSocket.readMessage
    WebSocketCall.java:152 io.intercom.okhttp3.ws.WebSocketCall.createWebSocket
    WebSocketCall.java:41 io.intercom.okhttp3.ws.WebSocketCall.access$000
    WebSocketCall.java:97 io.intercom.okhttp3.ws.WebSocketCall$1.onResponse
    RealCall.java:126 io.intercom.okhttp3.RealCall$AsyncCall.execute
    NamedRunnable.java:32 io.intercom.okhttp3.internal.NamedRunnable.run
    ThreadPoolExecutor.java:1133 java.util.concurrent.ThreadPoolExecutor.runWorker
    ThreadPoolExecutor.java:607 java.util.concurrent.ThreadPoolExecutor$Worker.run
    Thread.java:776 java.lang.Thread.run
```

**Comment by ronocod** [comment] 2017-05-15 09:20
Thanks for posting the new reports. We haven't been able to establish the cause of this yet, so we don't currently have a fix.

**Comment by jackcsk** [comment] 2017-05-16 09:06
Thanks for the info. So far, we have no new issue after upgrading to intercom 3.1.1

**Comment by AndreiZaitcev** [comment] 2017-05-31 08:31
@henrikra were you able to find the reason? I don't use intercom, but somehow got the same crashes for my app.

**Comment by henrikra** [comment] 2017-05-31 09:30
No not yet @AndreiZaitcev

**Comment by ronocod** [comment] 2017-09-08 12:45
This should be fixed in 4.x versions of the SDK, the OkHttp code around this has been updated.

**Closed by ronocod** 2017-09-08 12:45 UTC
