### ISSUE TITLE
Show error

### ISSUE THREAD

**Issue by noinlijin** [intercom/intercom-android#379] opened 2017-07-18 01:58 UTC
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Android version:3.2.8
  - Android OS version:7.0
  - Android Device:google nexus 6

## Steps to reproduce
 1. 
 2. 
 3. 
![image](https://user-images.githubusercontent.com/3073370/28297284-a9706866-6b9f-11e7-98b6-5aabb727cad9.png)

## Logs

**Comment by DaleCantwell** [comment] 2017-07-18 09:22
Thanks for reporting this, closing as a dupe of https://github.com/intercom/intercom-android/issues/378

**Closed by DaleCantwell** 2017-07-18 09:22 UTC
