### ISSUE TITLE
io.intercom.com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:284)

### ISSUE THREAD

**Issue by osama-taha** [intercom/intercom-android#436] opened 2017-10-09 07:32 UTC
## Version info
  - Intercom for Android version: 4.04
  - Android OS version: 4.4.4
  - Android Device: Samsung Galaxy Alpha

## Logs

Fatal Exception: java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
       at io.intercom.com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:284)
       at io.intercom.com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:124)
       at io.intercom.com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:109)
       at io.intercom.com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:113)
       at io.intercom.com.bumptech.glide.Glide.with(Glide.java:561)
       at io.intercom.android.sdk.utilities.AvatarUtils.createAvatar(AvatarUtils.java:63)
       at io.intercom.android.sdk.utilities.AvatarUtils.loadAvatarIntoView(AvatarUtils.java:44)
       at io.intercom.android.sdk.profile.TeammateProfilePresenter.setPresence(TeammateProfilePresenter.java:224)
       at io.intercom.android.sdk.profile.ProfilePresenter.setTeammatePresence(ProfilePresenter.java:107)
       at io.intercom.android.sdk.conversation.ConversationFragment.updateProfileToolbar(ConversationFragment.java:499)
       at io.intercom.android.sdk.conversation.ConversationFragment.conversationSuccess(ConversationFragment.java:713)
       at io.intercom.android.sdk.conversation.ConversationFragment.onConversationUpdated(ConversationFragment.java:617)
       at io.intercom.android.sdk.conversation.WebViewHostWrapper$1.run(WebViewHostWrapper.java:67)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5635)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by ronocod** [comment] 2017-10-09 09:17
Duplicate of https://github.com/intercom/intercom-android/issues/425, fixed in 4.0.5.

**Closed by ronocod** 2017-10-09 09:17 UTC
