### ISSUE TITLE
Crash in PreviewService

### ISSUE THREAD

**Issue by gennadiiivanov** [intercom/intercom-android#95] opened 2015-06-15 14:24 UTC
```
java.lang.RuntimeException: Unable to start service io.intercom.android.sdk.preview.PreviewService@41af4010 with Intent { cmp=com.livestream.livestream/io.intercom.android.sdk.preview.PreviewService }: java.lang.NullPointerException
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2742)
       at android.app.ActivityThread.access$1900(ActivityThread.java:148)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1348)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:151)
       at android.app.ActivityThread.main(ActivityThread.java:5211)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.NullPointerException
       at io.intercom.android.sdk.preview.PreviewService.checkConversations(PreviewService.java:263)
       at io.intercom.android.sdk.preview.PreviewService.onStartCommand(PreviewService.java:157)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2725)
       at android.app.ActivityThread.access$1900(ActivityThread.java:148)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1348)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:151)
       at android.app.ActivityThread.main(ActivityThread.java:5211)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by derek-cheung** [comment] 2015-06-16 11:38
Also getting this crash on our app, consistently on some screens (v1.0.4).

java.lang.RuntimeException: Unable to start service io.intercom.android.sdk.preview.PreviewService@18588143 with Intent { cmp=/io.intercom.android.sdk.preview.PreviewService }: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.isEmpty()' on a null object reference
           at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2911)
           at android.app.ActivityThread.access$2100(ActivityThread.java:151)
           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1401)
           at android.os.Handler.dispatchMessage(Handler.java:102)
           at android.os.Looper.loop(Looper.java:135)
           at android.app.ActivityThread.main(ActivityThread.java:5254)
           at java.lang.reflect.Method.invoke(Native Method)
           at java.lang.reflect.Method.invoke(Method.java:372)
           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
    Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.isEmpty()' on a null object reference
           at io.intercom.android.sdk.preview.PreviewService.checkConversations(PreviewService.java:263)
           at io.intercom.android.sdk.preview.PreviewService.onStartCommand(PreviewService.java:157)
           at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2894)
            at android.app.ActivityThread.access$2100(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1401)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by KeithYokoma** [comment] 2015-06-23 08:27
Same for me with `1.0.4`. Log says the service is going to use a null reference of List and causing `NullPointerException`.

```
    java.lang.RuntimeException: Unable to start service io.intercom.android.sdk.preview.PreviewService@274f9d0f with Intent { cmp=com.drivemode.android.debug/io.intercom.android.sdk.preview.PreviewService }: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.isEmpty()' on a null object reference
            at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2911)
            at android.app.ActivityThread.access$2100(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1401)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.isEmpty()' on a null object reference
            at io.intercom.android.sdk.preview.PreviewService.checkConversations(PreviewService.java:263)
            at io.intercom.android.sdk.preview.PreviewService.onStartCommand(PreviewService.java:157)
            at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2894)
            at android.app.ActivityThread.access$2100(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1401)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by harkin** [comment] 2015-06-23 09:29
Sorry for the delay in getting back to you on this, I'm investigating this crash now

**Comment by harkin** [comment] 2015-06-24 12:18
The service wasn't managing state properly when a process restarted, there will be a fix for this in the next release

**Comment by gennadiiivanov** [comment] 2015-06-24 13:14
@harkin have you fixed both reported crashes?

**Comment by harkin** [comment] 2015-06-24 13:51
@gennadiiivanov maybe I've missed something here, the three stack traces posted are all for the same crash (a null pointer exception on line 263 of the service)

**Comment by gennadiiivanov** [comment] 2015-06-24 14:28
@harkin , sorry, I've overlooked it. Yes, they are from the same crash.

**Comment by harkin** [comment] 2015-06-24 14:31
:+1:

**Comment by IlyaEremin** [comment] 2015-06-26 11:11
@harkin when do you plan to release new version?

**Comment by sureshjoshi** [comment] 2015-06-29 03:10
Why was this closed? I just got this crash in 1.0.4. Shouldn't it be closed when the fix is public?

    java.lang.RuntimeException: Unable to start service io.intercom.android.sdk.preview.PreviewService@110e3d5f with Intent { cmp=com.mioglobal.android.miogo/io.intercom.android.sdk.preview.PreviewService }: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.isEmpty()' on a null object reference
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2911)
       at android.app.ActivityThread.access$2100(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1401)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
    Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.isEmpty()' on a null object reference
       at io.intercom.android.sdk.preview.PreviewService.checkConversations(PreviewService.java:263)
       at io.intercom.android.sdk.preview.PreviewService.onStartCommand(PreviewService.java:157)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2894)
       at android.app.ActivityThread.access$2100(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1401)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by harkin** [comment] 2015-06-30 09:03
@IlyaEremin all going well, today or tomorrow

@sureshjoshi :+1: you're right, I reckon I hit the wrong button :(

**Comment by sureshjoshi** [comment] 2015-06-30 23:54
Please tell me this fix is coming soon. I got 148 crashes TODAY on this.

**Comment by harkin** [comment] 2015-07-01 15:58
the new version is up now

**Closed by harkin** 2015-07-01 15:58 UTC

**Comment by sureshjoshi** [comment] 2015-07-02 21:12
Could we get some feedback as to what caused this issue and how it escaped testing? It chalked up 7300 crashes across 1700 users of my app - reaching level 5 in Crashlytics (first time I've seen a level 5 error)

I've backed out intercom entirely for the time being, until it stabilized, but some insight into how these crashes are introduced and what testing is going on would go a long way to ease my fears about re-introducing intercom in a few months.

**Comment by harkin** [comment] 2015-07-07 17:31
We made some changes to our service that manages notifications when an app is open that involved changing how it managed some state. There was a reference to a list that wasn't being restored correctly after the service was killed and restarted when the app was backgrounded (typically caused by a process restart) which lead to the null pointers. I'm surprised you saw it happen so frequently. 

I'm doing an audit of the library to ensure there aren't any other bugs like this. We're looking into how we can test for this kind of bug in future.

**Comment by sureshjoshi** [comment] 2015-07-07 18:29
@harkin Thanks for the candor, really appreciate it!!
