### ISSUE TITLE
Click on push does nothing

### ISSUE THREAD

**Issue by danikula** [intercom/intercom-android#260] opened 2016-09-20 17:59 UTC
## Version info
- Intercom for Android version: **3.0.9**
- Android OS version: **6.0.1**
- Android Device: **Nexus 5**
## Expected behavior

Click on push notification about new conversation/reply should open corresponding conversation.
## Actual behavior

Click on push notification about new conversation/reply does nothing, just cancel notification.
## Steps to reproduce
1. Move app to background. 
2. Reply on conversation.
3. Wait for push and tap on it. Nothing happen.

**Comment by ronocod** [comment] 2016-09-21 14:49
Trying to reproduce this and https://github.com/intercom/intercom-android/issues/261 now.

**Comment by jessexx** [comment] 2016-09-22 21:22
I'm having the same issue.  Using GCM and in `onMessageReceived()` of the GCMListenerService,  I am calling `intercomPushClient.handlePush(getApplication(), data)`.  This is creating a push notification properly, but clicking it does nothing.

**Comment by danikula** [comment] 2016-09-26 13:55
@ronocod Any news?

**Comment by ronocod** [comment] 2016-09-26 14:05
Haven't found out anything conclusive on this so far.

Does your app have an Activity which handles `CATEGORY_INFO` or `CATEGORY_LAUNCHER`? If you can launch your app from the homescreen then the answer will be yes.

**Comment by danikula** [comment] 2016-09-26 14:18
Yes, I have haunch activity with intent filter
```
<intent-filter>
    <action android:name="android.intent.action.MAIN" />
    <category android:name="android.intent.category.LAUNCHER" />
</intent-filter>
```

**Comment by jessexx** [comment] 2016-09-26 20:21
I have a `LAUNCHER` activity but it's not the same activity that I would like to handle the push in.

**Comment by jessexx** [comment] 2016-09-27 14:58
I changed my gradle to `compile 'io.intercom.android:intercom-sdk:3.0.8'` and clicking the push notification seems to be working again.  Seems the issue only started with the latest update.

**Comment by ronocod** [comment] 2016-09-27 15:06
@jessexx thanks, I'll look into which changes might have caused this

**Comment by danikula** [comment] 2016-09-29 10:43
The issue is reproduced on `3.0.8` too.

**Comment by ronocod** [comment] 2016-10-05 12:09
3.0.10 has some better logging in this area, can you try to reproduce on that version and see if you get any log messages when tapping on the notification?

**Comment by jessexx** [comment] 2016-10-05 14:52
I encountered an initial crash that I can't reproduce now.  It happened on `Intercom.initialize()` and the log had something like FieldDoesNotExist exception for Intercom-birdy-done1.  I tried to reproduce it on another test device before logging the issue and it has not happened since.  The device that crashed was a Nexus5x running 7.0 if that helps.  Will let you know if I encounter it again and grab the logs.

**Comment by ronocod** [comment] 2016-10-05 14:54
@jessexx what version of the SDK did this happen with?

**Comment by jessexx** [comment] 2016-10-05 14:55
@ronocod this was immediately after changing gradle to `compile 'io.intercom.android:intercom-sdk:3.+'` when I saw that 3.0.10 was out.

**Comment by ronocod** [comment] 2016-10-05 14:57
Hmm ok, I'll have a look into that.

**Comment by jessexx** [comment] 2016-10-05 15:27
Back to push notifications, it seems notification clicks are working properly in 3.0.10.  I do not see any extra logs but so far none of the notifications have failed.

**Comment by ronocod** [comment] 2016-10-05 15:36
Great! If @danikula also finds them to be fixed then I'll close this issue. Please make an issue for the FieldDoesNotExist exception if it happens again too :)

**Comment by danikula** [comment] 2016-10-09 14:29
This problem is reproduced in 3.0.10 too. But I think this issue is related to using [urbanairship](https://www.urbanairship.com/). When I totally disable urbanairship clicking on intercom push messages works well. So I gonna try to investigate into this problem little bit deeply and will report about results here.

**Comment by emmaguy** [comment] 2016-10-24 16:29
I'm seeing the same issue on `3.0.10` when clicking on notifications that are not grouped - so just a single message. Grouped ones worked okay.

Have just implemented creating the notification and opening intercom ourselves for now. The intercom notification from the sdk wasn't using our icon either (even when I made one with the name from the documentation)

**Comment by emmaguy** [comment] 2016-10-31 18:15
I contacted Intercom support about this, who suggested tagging @ronocod about ☝️

**Comment by ronocod** [comment] 2016-11-01 10:12
Hi 😄 

Sorry about the delay in getting back to you about this, we've never been able to reproduce this issue ourselves but seeing as it's continuing to be an issue I'll look into it more this week.

Are you using FCM or GCM?

**Comment by emmaguy** [comment] 2016-11-01 10:22
We're using GCM

**Comment by oiramcro** [comment] 2016-11-02 06:48
Hi, I am also facing this issue.

And it can be easily reproduced when you send messages to a user. I was able to do this in this steps:

1. Send multiple messages ( 3 or 4 )  to a single user.
2. User clicks on push message notification and opens regular chat screen
3. User puts app in the background
4. Admin in the same time sends another 3 or 4 messages to user 
5. Users clicks on the push msg notification and nothing happens.

**Comment by ronocod** [comment] 2016-11-07 15:18
Just a quick update on this: we're still trying to reproduce this locally but we haven't yet been able to. From seeing this happen in other apps it seems that our BroadcastReceiver which handles the clicks isn't receiving the Intent which is fired when the click happens. We'll continue investigating this, and any more information that can be provided would be great.

**Comment by ronocod** [comment] 2016-11-18 17:48
We made a change in version 3.0.13 that may fix this, could you try that and let me know if this bug is still present?

**Comment by ronocod** [comment] 2016-12-06 10:29
Has anyone been able to reproduce this in 3.0.13 or above? Would love to know for sure that this is fixed.

**Comment by ronocod** [comment] 2016-12-12 12:47
Closing this as we've had no reports of this happening since 3.0.13 was released.

**Closed by ronocod** 2016-12-12 12:47 UTC

**Comment by SlobodanNikolic** [comment] 2017-01-26 10:42
And what was the problem?

**Comment by ronocod** [comment] 2017-01-26 10:59
We switched from using the `FLAG_CANCEL_CURRENT` flag in `PendingIntent.getBroadcast()` to `FLAG_UPDATE_CURRENT`
